### ISSUE TITLE
Variables in the global scope.

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2-app-basic#10]
:frowning:

```
<?= $GLOBALS['params']['adminEmail']; ?> // admin@example.com
``` 

___
`$config` from `index.php` and `param` from `web.php` are stored in the global scope throughout the life of the application. No sense.

![image](https://cloud.githubusercontent.com/assets/874234/7662240/cd63b49e-fb62-11e4-8b45-0fc8f5187bc4.png)

Propose:
```php
(new yii\web\Application(require __DIR__ . '/../config/web.php'))->run();
```

```php
'params' => require __DIR__ . '/params.php',
```

**Comment by cebe** [comment]
whats the problem with this?

**Comment by githubjeka** [comment]
Why should they take place, if 100% of cases are not used.

**Comment by samdark** [comment]
Wouldn't they take the same amoun of memory with your proposed change applied?

**Comment by githubjeka** [comment]
Now 3321**496** bytes, after delete `$params` and `$config` 3321**344** bytes. 

But in `web.php`
```php
$config = [
    ....
    'params' => require __DIR__ . '/params.php',
];

if (YII_ENV_DEV) {
    ....
}
return $config;
```

and `$config` still remains in the memory. I can not think how to do unset ` $config`. 


#### About $params
Now you can get `param` via:

```php
var_dump(Yii::$app->params, $GLOBALS['params'], $GLOBALS['config']['params']);
```

<pre class="xdebug-var-dump" dir="ltr"><b>array</b> <i>(size=1)</i>
  'adminEmail' <font color="#888a85">=&gt;</font> <small>string</small> <font color="#cc0000">'admin@example.com'</font> <i>(length=17)</i>
</pre>

<pre class="xdebug-var-dump" dir="ltr"><b>array</b> <i>(size=1)</i>
  'adminEmail' <font color="#888a85">=&gt;</font> <small>string</small> <font color="#cc0000">'admin@example.com'</font> <i>(length=17)</i>
</pre>

<pre class="xdebug-var-dump" dir="ltr"><b>array</b> <i>(size=1)</i>
  'adminEmail' <font color="#888a85">=&gt;</font> <small>string</small> <font color="#cc0000">'admin@example.com'</font> <i>(length=17)</i>
</pre>

I see no reason to use a long string `Yii::$app->params`.:trollface:

**Comment by cebe** [comment]
I do not think that 152 bytes of memory is something we should really care about.

**Comment by githubjeka** [comment]
Ok :)
