### ISSUE TITLE
Use https link to clone dependencies instead of ssh link by default. 

### ISSUE THREAD

**Issue by AAlvz** [yiisoft/yii2-app-basic#102]
If I don't want to create a token nor use an ssh key, the dependencies should be able to download using https links by default. Currently jquery dependency point to `git@github.com:jquery/jquery-dist.git` by default and there's no file to modify and to use https instead for dependencies. 

### What steps will reproduce the problem?
1. DON'T HAVE A COMPOSER TOKEN
2. 
```
git clone https://github.com/yiisoft/yii2-app-basic.git
cd yii2-app-basic
php composer.phar global require "fxp/composer-asset-plugin:^1.2.0"
php composer.phar create-project --prefer-dist --no-interaction --stability=dev yiisoft/yii2-app-basic basic
```

### What's expected?
1. To download without problems every dependence.
2. Have a basic yii app ready to run.

### What do you get instead?
```
Installing yiisoft/yii2-app-basic (dev-master b3e97d79406ae1b74dc66acbbf76d516fb8d81a2)
  - Installing yiisoft/yii2-app-basic (dev-master master) Loading from cache
Created project in basic
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to clone the git@github.com:jquery/jquery-dist.git repository, try running in interactive mode so that you can enter your GitHub credentials

                                                                                                                                                              
  [RuntimeException]                                                                                                                                          
  Failed to execute git clone --mirror 'git@github.com:jquery/jquery-dist.git' '/home/tinkerware/.composer/cache/vcs/git-github.com-jquery-jquery-dist.git/'  
                                                                                                                                                              

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

```

### Additional info

This happens due to a dependency pointing to an ssh direction (`git@github.com:jquery/jquery-dist.git`). 

There should be a file to update this route to use `https` and/or place the https link by default (`https://github.com/jquery/jquery-dist.git`) for the cases when we don't want to use keys nor token.

| Q                | A
| ---------------- | ---
| Yii version       | 2
| PHP version      |  PHP 5.6.29-0+deb8u1
| Operating system | Debian 8 - Jessie

**Comment by cebe** [comment]
have you tried `composer install --prefer-dist` ?

**Comment by AAlvz** [comment]
@cebe of course I've tried. Up there you can see how I'm running the composer command in the section with the steps to reproduce the problem

**Comment by samdark** [comment]
I don't think there's a way for us to affect the protocol used by composer. @AAlvz if you have any ideas we'll be glad to reopen the issue.

**Comment by AAlvz** [comment]
@samdark maybe you could guide me? Where are these dependencies defined? That way we could track why this is happening. AFAIU, this is not default composer behavior, is it?... That dependency should be defined somewhere...

**Comment by cebe** [comment]
@AAlvz can you try to run that command with `-vvv` and paste the output? Running it for me downloads a zip file via HTTP, which is what it should because of `--prefer-dist`.

**Comment by AAlvz** [comment]
@cebe Did you try running that command and making sure you don't have any composer token in github? to reproduce this, the composer token should be removed..

**Comment by AAlvz** [comment]
There's a lot of output but here is what I consider the relevant part

```
Reading /home/user/.composer/cache/repo/https---packagist.org/provider-bower-asset$jquery.json from cache
Downloading https://bower.herokuapp.com/packages/jquery
Writing /home/user/.composer/cache/repo/https---bower.herokuapp.com-packages/jquery-6f2ab963b5a51d155d69ac091e52e506d1055057-package.json into cache
Adding VCS repository bower-asset/jquery
Downloading https://api.github.com/repos/jquery/jquery-dist
Downloading https://github.com/jquery/jquery-dist
Downloading https://api.github.com/repos/jquery/jquery-dist
Executing command (CWD): git config github.accesstoken
Executing command (CWD): git clone --mirror 'git@github.com:jquery/jquery-dist.git' '/home/user/.composer/cache/vcs/git-github.com-jquery-jquery-dist.git/'
Executing command (CWD): git config github.accesstoken
Executing command (CWD): git --version
Failed to clone the git@github.com:jquery/jquery-dist.git repository, try running in interactive mode so that you can enter your GitHub credentials

                                                                                                                            
  [RuntimeException]                                                                                                        
  Failed to execute git clone --mirror 'git@github.com:jquery/jquery-dist.git' '/home/user/.composer/cache/vcs/git-g  
  ithub.com-jquery-jquery-dist.git/'                                                                                        
                                                                                                                            

```

If you need something else please tell me :)

**Comment by cebe** [comment]
On a completely plain system (newly created lxc container running debian stretch), I do the following:

1. Install PHP, install composer.
2. ```
    $ composer global require "fxp/composer-asset-plugin:^1.2.0"
    ...
    $ composer --version
    Composer version 1.3.2 2017-01-27 18:23:41
    $ composer global show     
    Changed current directory to /home/cebe/.composer
    fxp/composer-asset-plugin v1.2.2 NPM/Bower Dependency Manager for Composer
```

I am now able to reproduce the issue with either of the following commands:

     composer create-project --prefer-dist --no-interaction --stability=dev yiisoft/yii2-app-basic basic
     composer create-project --prefer-dist --no-interaction --stability=stable yiisoft/yii2-app-basic basic2

**Comment by cebe** [comment]
This is not an issue with yii but with composer or the asset plugin so it should be reported there. I found an issue which sounds like it is the same as this one: https://github.com/fxpio/composer-asset-plugin/issues/212
