### ISSUE TITLE
composer exec codecept run return nothing after a fresh install

### ISSUE THREAD

**Issue by paralaks** [yiisoft/yii2-app-basic#104]
### What steps will reproduce the problem?
Install basic template as described in the README.md and set real db parameters in config/db.php
Execute: composer exec codecept run
### What's expected?
Something; failure, error, warning
### What do you get instead?
Nothing
### Additional info
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.11-dev
| PHP version      | 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
| Operating system | Ubuntu 16.04

**Comment by Sarke** [comment]
I just had the same problem.  Maybe it's a new issue with composer?

I created an issue with them, where it's suggested that `composer exec` should not be used: 

https://github.com/composer/composer/issues/6122

To see what the error was you need to use `composer -v exec codecept run`

**Comment by cebe** [comment]
seems composer just supresses the output. because with `-v` everything runs just fine for me.

**Comment by cebe** [comment]
Adjusted the docs to not use `composer exec`. Thanks for reporting!

**Comment by samdark** [comment]
Thanks @Sarke. While it's being fixed, I think we can use binary from vendor directory in docs.

**Comment by cebe** [comment]
@samdark I have already changed that :)

**Comment by samdark** [comment]
Oh :)
