### ISSUE TITLE
Do you have any plans to implement/integrate environments mechnism in basic app just like one in the advance app?

### ISSUE THREAD

**Issue by mfuzailzubari** [yiisoft/yii2-app-basic#105]
I want to know that if yii2 team is working or planning to work on the environment mechanism in the yii2 basic application just like one exist in the advance application. I have usually seen people using yii2 basic application for REST APIs. While deployment they face issues like params mis-match etc. So I think we should handle the environment in basic application the same way we handle it in the advance application. If you people are not working on it, do let me know I will create a merge request.

Thanks,

**Comment by mfuzailzubari** [comment]
@rob006 what do you suggest on this.

Thanks,

**Comment by rob006** [comment]
I already proposed this (#60), but it was rejected as too complex. End up with my own template: https://github.com/rob006/yii2-app-extended .

**Comment by samdark** [comment]
Planned for 2.1. Not going to implement it in 2.0.14.
