### ISSUE TITLE
Link structure duplicates with index.php

### ISSUE THREAD

**Issue by inwoker** [yiisoft/yii2-app-basic#109]
### What steps will reproduce the problem?
Install yii. Create htaccess like the one in manual.
In UrlManager: 'enablePrettyUrl' => true, 'showScriptName' => false, 'enableStrictParsing' => false,
Then open http://yourdomain.com/index.php or any page http://yourdomain.com/index.php/any-page
### What's expected?
I guess, to redirect to pages without index.php or throw 404 exception. That's up to debate.

### What do you get instead?
It works and creates page duplicates.

### Additional info
Lastest yii 2.0.11, php 5.6, apache. Same with nginx and default config.

**Comment by cebe** [comment]
> I guess, to redirect to pages without index.php or throw 404 exception. That's up to debate.

you could set up your .htaccess file to do this.

**Comment by inwoker** [comment]
> you could set up your .htaccess file to do this.
I guess. I just wanted to know if yii developers are aware of this. And maybe you should do something about it or not.

For example, you can setup removing/adding slashes in htaccess, but recently you released url normalizer which does this. So maybe something would be done on yii core level to remove index.php.

If not, and you guys don't consider it a bug, I suppose I would just find a solution for htaccess and use it in all my projects. Though probably, I can then write it here and it can be added to setup manual, for both htaccess and nginx config.

**Comment by inwoker** [comment]
@samdark Do I understand correctly that this will be fixed?

**Comment by samdark** [comment]
It will be documented on how to achieve it using a webserver at least.

**Comment by inwoker** [comment]
Working solution for 301 redirect:
RewriteEngine On

RewriteCond %{THE_REQUEST} ^GET.*index\.php [NC]
RewriteRule (.*?)index\.php/*(.*) /$1$2 [R=301,NE,L]

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ index.php [L]

The only downside to this solution is that it redirects http://example.com/index.php/non-existing-url to http://example.com/non-existing-url instead of just showing 404. So I guess, more correct solution would be to do it on framework level. Or we can return 404 on server level, instead of 301 redirect for these cases.

**Comment by cebe** [comment]
Made an adjustment to the htaccess file in the guide, with a rule that works on / as well as subdirectories. Thanks for reporting and the solution!
