### ISSUE TITLE
Почему необходимо добавлять в настройку config/test.php AssetManager::basePath

### ISSUE THREAD

**Issue by damasco** [yiisoft/yii2-app-basic#110]
```
'assetManager' => [
    'basePath' => __DIR__ . '/../web/assets',
],
```
и почему не работают стандартные настройки? 
Спасибо.

**Comment by damasco** [comment]
Я думаю что не очень хорошо, когда файл конфига явно знает `@webroot`.

**Comment by SilverFire** [comment]
Потому что тесты и выполняемый файл для них находится в поддиректории `tests`, потому нужно модифицировать этот параметр.

Я пока закрываю эту issue, но если у вас есть более основательное объяснение - напишите его и мы рассмотрим его.
