### ISSUE TITLE
Include composer.lock (at least in releases)

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-app-basic#112]
### What steps will reproduce the problem?

Install (create-project) an old version of this app.

### What's expected?

Always a working app with locked extensions.

### What do you get instead?

Currently composer runs an update which will resolve the extension constraints to their latest version, which might be an untested combination.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | any
| PHP version      | any
| Operating system | any

> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then. (See note below about using the update command.)

References:
- https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
- http://stackoverflow.com/questions/12896780/should-composer-lock-be-committed-to-version-control

CC: @mikehaertl

**Comment by mikehaertl** [comment]
We already discussed this in private, so here's my point of view:

The template is not a regular project. It's a *template* to create a project. Not every developer in your team will start from the template but *one* developer will create your initial app repo. When doing so, he wants to be sure, to get the latest versions for all dependencies. It's at that point when the `composer.lock` is created and then should be submitted to *your* repo - that's what that paragraph from the composer docs is all about.

If you commit the `composer.lock` here, you'd have to update it on a regular basis in order to make sure, that you get the latest versions of all dependencies.

**Comment by mikehaertl** [comment]
@schmunk42 How would you deal with subsequent updates of dependencies between yii2 releases? Say yii-app-basic 2.0.11.2 is out, but there's an updated version for `yii2-bootstrap`. What should we do now?

**Comment by schmunk42** [comment]
The main developer can still run `composer update` when he wants to.

**Comment by schmunk42** [comment]
> How would you deal with subsequent updates of dependencies between yii2 releases?

That's not an issue with a `.lock` file, as said above - just run `composer update` or even `composer update yiisoft/yii2-bootstrap` if you just want to update one package.

**Comment by dynasource** [comment]
shouldnt the unit tests for the app already be sufficient  to make sure the dependencies work ok? 

Also, updating this .lock file in GIT is challenging.

**Comment by cebe** [comment]
> Install (create-project) an old version of this app.

why would you create a new project from an old version?

**Comment by schmunk42** [comment]
> why would you create a new project from an old version?

I always create new projects from **stable** (locked) versions, not from latest (even if their constraints are stable).

**Comment by schmunk42** [comment]
> Also, updating this .lock file in GIT is challenging.

What is challenging about this?

**Comment by dynasource** [comment]
who's responsible for updating it?

**Comment by schmunk42** [comment]
If you've changes to `composer.json` you need to update the `.lock` file. Composer will complain anyway about this.

The rest is policy or convention. I'd recommend to update, when preparing a release, but you can update it at anytime.

We could also run tests with `composer install` and `composer update` which would tell us, when an update would introduce breaks.

More pros for the .lock file:
- installation is much much faster
- no composer plugins required at all (for install)
- less moving parts, less things break

**Comment by rob006** [comment]
> I always create new projects from stable (locked) versions, not from latest (even if their constraints are stable)

Why do you think that old (stable) dependencies will be more stable than new (stable) dependencies? It could be quite opposite - last release of this template was 1st February, after Yii 2.0.11 but before two patch releases (2.0.11.1 and 2.0.11.2). In this case `composer.lock` will contain old version of Yii 2 with known and fixed bugs - it will be less stable than now.

**Comment by schmunk42** [comment]
> Why do you think that old (stable) dependencies will be more stable than new (stable) dependencies?

I mean stable as a set of extensions, for which dependencies (SAT) has been resolved already and for which (also integration-) tests have been passed.

It's no question that we update our apps to fix bugs, etc. 

But with `update` almost every package is a moving target and you rely on the fact that every developer for every lib does not introduce a breaking change accidentally (happened even to Yii). That should simply not be a default or enforced to the user.

Moreover there are edge-cases in which composer might run into like 50/50 decisions which can be very hard to debug. I had to limit updates to Yii < 2.0.10 for a certain lib for example, but because older versions of my lib did not have the constaint you can either end up with:

- Yii 2.0.10 + lib 0.3.0
- Yii 2.0.9 + lib 0.3.2
- Yii 2.0.11 + lib 0.4.0-beta1

All valid, but the outcome or final decision is influenced by many factors.

**Comment by rob006** [comment]
You can just download archive with template snapshot from http://www.yiiframework.com/download/ ("Install from an Archive File" section).

>  I had to limit updates to Yii < 2.0.10 for a certain lib for example

How locking dependencies in template will help with this? v2.0.11 will still install Yii 2.0.11. 
If you need lock some dependency, you should do this in `composer.json` anyway.

**Comment by schmunk42** [comment]
> You can just download archive with template snapshot from http://www.yiiframework.com/download/ ("Install from an Archive File" section).

Oh, good to know. But the `.lock` file would be sufficient - unless GitHub is down ;)

> How locking dependencies in template will help with this? v2.0.11 will still install Yii 2.0.11.
If you need lock some dependency, you should do this in composer.json anyway.

I didn't lock the version in the template in the case above, I limited the constraint in a lib.

Btw. the Yii app-templates and Yii 2.0 Framework have a slightly different versioning.

Saying that `v2.0.11` will install Yii `2.0.11` is already incorrect ;) since you get `2.0.11.2` 😋 
If you would have said this by the time `2.0.1` came out ... try this: just as an example `composer create-project yiisoft/yii2-app-basic:2.0.1` will give you the framework in `2.0.11.2` (or whatever current version or your minimum stability is active at the moment) - or in fact it could be any other version. A bit theoretical, but [a missing c-type](https://github.com/yiisoft/yii2/commit/33f86b39133b21eab66ebb7476bbfd8d7599c38e) extension might cause a fall-back to 2.0.7...

You can argue if that is what *you* want, but with a `.lock` file you can run `create-project --no-install` and afterwards `composer update`.

Locking dependencies simply helps that things don't break. I usually say: "Composer update fixes and breaks things, composer install just works."

**Comment by rob006** [comment]
> Oh, good to know. But the .lock file would be sufficient - unless GitHub is down ;)

But why do you want to use composer in that case? Downloading single archive is faster and more reliable. 

> Locking dependencies simply helps that things don't break.

No, it's not. Dependencies are resolved in specified environment - if you build lock on php 7, you may not be able to install it in php 5.6. Same with installed extensions. 

Anyway, it looks like you're trying to solve problem (that is already solved) by solution which creates bunch of new problems. Lets keep composer-way for people that actually want to resolve dependencies, and archive-snapshot for people that just want to download working but old template.

**Comment by schmunk42** [comment]
> if you build lock on php 7, you may not be able to install it in php 5.6. Same with installed extensions.

Sure, that's exactly what should happen. You need to update in that case and check & test a your app completely.

> Anyway, it looks like you're trying to solve problem (that is already solved) by solution which creates bunch of new problems. Lets keep composer-way for people that actually want to resolve dependencies, and archive-snapshot for people that just want to download working but old template.

I've nothing more to add, than to quote one of the initial links in full, again.

> > ### Commit Your composer.lock File to Version Control
> > Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using. Your CI server, production machines, other developers in your team, everything and everyone runs on the same dependencies, which mitigates the potential for bugs affecting only some parts of the deployments. Even if you develop alone, in six months when reinstalling the project you can feel confident the dependencies installed are still working even if your dependencies released many new versions since then. (See note below about using the update command.)

Not using a lock file is not recommended by composer-devs, slow, error-prone and unpredictable. It does not create new problems, it just gives you the option to actually install an application via [create-project](https://github.com/yiisoft/yii2-app-basic#install-via-composer) and not be **forced** to run an update.

**Comment by rob006** [comment]
> Sure, that's exactly what should happen. You need to update in that case and check & test a your app completely.

Which tests? This is only template with 3 dependencies and some basic tests. To make real app from this template you need add own logic, own tests, and custom dependencies. Initial lock will not help in this at all, only makes installation harder and more fragile.

**Comment by schmunk42** [comment]
> Which tests?

https://github.com/yiisoft/yii2-app-basic/tree/master/tests

> This is only template with 3 dependencies

`composer show | wc -l` ... I count 19.

> only makes installation harder and more fragile.

No :) It's running an installation from a flat file vs. making dozens of HTTP calls, git checkout prune whatever, dependency resolution of 1000s of rules. Not even taken into account that it's magnitudes faster.

**Comment by cebe** [comment]
> Committing this file to VC is important because it will cause anyone who sets up the project to use the exact same versions of the dependencies that you are using.

That is the reason why composer.lock is not in .gitignore and should be committed once the project is created. The purpose of the application template is to be used as a basis for a new project. I see no point in creating a project using older versions than are available at the point of creation.

The only argument that would count here (as far as I see) is, that it would be faster. however we need to force people into using PHP 5.4 compatible dependencies then, while PHP 7 would be recommended so I do not think this is a good idea.

**Comment by samdark** [comment]
I agree with @cebe.

**Comment by schmunk42** [comment]
> That is the reason why composer.lock is not in .gitignore and should be committed once the project is created. The purpose of the application template is to be used as a basis for a new project. I see no point in creating a project using older versions than are available at the point of creation.

I fail to see, why should this **not** be a valid use-case. At the moment you'll never get the same dependencies when using the archive vs. cloning/downloading from GitHub. That can get confusing.

> The only argument that would count here (as far as I see) is, that it would be faster.

Absolutely not the only one and you're not loosing anything when having a lock file, since an `update` would do what **you** expect.

> however we need to force people into using PHP 5.4 compatible dependencies then, while PHP 7 would be recommended so I do not think this is a good idea.

Sorry, I didn't get that. Why is a lock file enforcing 5.4 dependencies?! The opposite is the case, with a lock file you get an error or warning if it platform-reqs not match for example. *Without* a lock file composer might resolve your deps to completely different versions.

> About stability, I would expect later stable versions to be more bugfree than old stable versions.

I *would expect* this also, but the reality is different, I had like a dozen of cases where an update broke things.

> At project start, it is more important imo to start from the latest dependencies available at that point (because why upgrade later which needs to change your code again?) than to have something 100% stable. It is not going to go to production right away.

As said, having a .lock file is not keeping you from doing this. Not having it simply leaves no other choice.

**Comment by samdark** [comment]
> I fail to see, why should this not be a valid use-case. At the moment you'll never get the same dependencies when using the archive vs. cloning/downloading from GitHub. That can get confusing.

@schmunk42 you're the only one mentioned it so far so I think it's not as confusing.

> Absolutely not the only one and you're not loosing anything when having a lock file, since an update would do what you expect.

That would increase number of actions to get the most up to date starting dependencies. Now it's just `composer create-project`. Then it would be additional step. That's probably OK if there's any gain which I don't personally see.

> Sorry, I didn't get that. Why is a lock file enforcing 5.4 dependencies?! The opposite is the case, with a lock file you get an error or warning if it platform-reqs not match for example. Without a lock file composer might resolve your deps to completely different versions.

If I'll do update while having PHP7 and push it then people with PHP 5.4 or even 5.6 won't be able to install Yii at all. So we'll have to generate lock file using PHP 5.4. Resolving to completely different versions in this case is exactly what's needed.

> I would expect this also, but the reality is different, I had like a dozen of cases where an update broke things.

Yes but with a project template you are **not** updating. You're using it to kickstart **new** project.

**Comment by cebe** [comment]
> I fail to see, why should this not be a valid use-case. At the moment you'll never get the same dependencies when using the archive vs. cloning/downloading from GitHub. That can get confusing.

can you explain why this is a problem? How often does the same person start a new project that has the exact same requirements?

> The opposite is the case, with a lock file you get an error or warning if it platform-reqs not match for example.

We do not have specific platform requirements for our users, so a new project would always start with something that is BC with PHP 5.4, excluding new PHPUnit versions for example. This is not what most users want, so after creating the yii project with a lock file they need to adjust composer.json platform spec and run composer update. This step is not needed if we do not ship a lock file.
The current way serves the most common use case imo.

**Comment by schmunk42** [comment]
> you're the only one mentioned it so far so I think it's not as confusing.

I think I am the only one, who noticed that ;)

> That would increase number of actions to get the most up to date starting dependencies. Now it's just composer create-project. Then it would be additional step. That's probably OK if there's any gain which I don't personally see.

Please have a look at the [composer docs](https://getcomposer.org/doc/03-cli.md#create-project)

> > You can use Composer to create new projects from an existing package. This is the equivalent of doing a git clone/svn checkout followed by a "composer install" of the vendors.

An `install` is not what is happening when you have no `.lock` file - it's an `update`.

> If I'll do update while having PHP7 and push lock file then people with PHP 5.4 or even 5.6 won't be able to install Yii at all. So we'll have to generate lock file using PHP 5.4. Resolving to completely different versions in this case is exactly what's needed.

Hmm, that's an edge-case in my Docker-world :) But I'd like to see an example for this. Could you provide a `composer.json` where this is required. IMHO it's not a good idea to develop on different major versions.

> Yes but with a project template you are not updating. You're using it to kickstart new project.

Now, that's actually my point :) 

Without a `.lock` for you are forced to update. And you're far away from **kickstarting** it. 
You need the asset-plugin, a GitHub token and a lot of time. A kickstart would look to me like:

    docker run -v ${PWD}:/app -it composer create-project phundament/app

A vanilla composer, installing a Yii2 application template with 71 packages in about 1 minute, without any additional setup.

---

> can you explain why this is a problem? How often does the same person start a new project that has the exact same requirements?

The example is about Developer A who says: "Hey, I downloaded Yii2, ran composer install and boom - it worked like 10 seconds later" (Note: he was downloading the archive). Developer B does the source download from GitHub and gets frustrated because he first gets an error saying that there are no bower-assets, after installing fxp, he'll run into the GitHub API token error. After that he has to wait several minutes to get his application running.

> We do not have specific platform requirements for our users, so a new project would always start with something that is BC with PHP 5.4, excluding new PHPUnit versions for example.

Maybe I am overlooking something here, same as above, I'd like to see an example for problematic use-case. The PHP version installed (locked) on is AFAIK not stored in the `.lock` file.

**Comment by cebe** [comment]
> Hmm, that's an edge-case in my Docker-world :) But I'd like to see an example for this. Could you provide a composer.json where this is required.

1. remove these lines from yiisoft/yii2 composer.json: https://github.com/yiisoft/yii2/blob/master/composer.json#L95-L97
2. run composer update on PHP 7
3. try to composer install the resulting lockfile on PHP 5
4. It will fail to install

> IMHO it's not a good idea to develop on different major versions.

It is not a good idea from the point where the application template was turned into a project. But Yii supports multiple PHP versions so we have to support stating a new project on different versions.
The best way to support this is to create composer.lock at that point where template becomes project imo.

> You need the asset-plugin, a GitHub token and a lot of time.

In case of a docker container that could be installed already. And you need the asset plugin installed anyway, this will only delay the installation.

**Comment by samdark** [comment]
@schmunk42 docker is good but I'm afraid not even half of Yii community are using it. I'd say much less.

**Comment by schmunk42** [comment]
What I am saying here has **nothing to do with Docker**. I just showed some examples, because you can easily try out vanilla or older versions of composer and PHP with it.

I am trying to reproduce the issue @cebe showed....

**Comment by schmunk42** [comment]
@cebe I tried what you mentioned and yes it fails. But ...

Why is this setting there in the first place? 

It does *fake* the PHP version for everyone down to 5.4, which gives you i.e. `symfony/yaml v2.8.18` - because v3 requires PHP `>=5.5.9`. No matter which version you have. 
Sidenote here: v2 has a lot of bugs compared to v3 (I often use this lib), so this contradicts many points you said before about getting the newer packages.

This setting only makes sense, when creating a `.lock` file *compatible* down to 5.4, since even an `update` on 7.1 would install/lock only packages compatible with 5.4 older versions.

This should be removed or at least raised to `5.6`, see http://php.net/supported-versions.php - even if Yii2 still runs with `5.4`, you should not encourage people to use a completely unsupported version or install old versions. You already have a requirement for `php >= 5.4.0`.

If somebody needs that - do it in your project. To me this is a project only setting, when developing on different versions. But clearly nothing for the template. I read though the original issue: https://github.com/yiisoft/yii2/issues/12946 - but haven't had time to debug this in full.

---

Addon, installation with faked 5.4, then removed the setting, look how outdated the versions are, despite an `update`:

```
> composer show -o
bower-asset/jquery                2.2.4   3.2.1
bower-asset/punycode              v1.3.2  v2.1.0
phpdocumentor/reflection-docblock 2.0.4   3.1.1
phpunit/php-code-coverage         2.2.4   5.0.3  Library that provides collection, processing, and rendering functionality for PHP code coverage...
phpunit/phpunit                   4.8.35  6.0.10 The PHP Unit Testing framework.
phpunit/phpunit-mock-objects      2.3.8   4.0.1  Mock Object library for PHPUnit
sebastian/comparator              1.2.4   2.0.0  Provides the functionality to compare PHP values for equality
sebastian/environment             1.3.8   2.0.0  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                1.2.2   3.0.0  Provides the functionality to export PHP variables for visualization
sebastian/recursion-context       1.0.5   3.0.0  Provides functionality to recursively process PHP variables
sebastian/version                 1.0.6   2.0.1  Library that helps with managing the version number of Git-hosted PHP projects
symfony/yaml                      v2.8.18 v3.2.6 Symfony Yaml Component
```

**Comment by schmunk42** [comment]
Also related: https://github.com/yiisoft/yii2/pull/13239

**Comment by samdark** [comment]
> Why is this setting there in the first place?

https://github.com/yiisoft/yii2/blob/master/framework/composer.json there's no such thing in the actual package that users are getting.

> Sidenote here: v2 has a lot of bugs compared to v3 (I often use this lib), so this contradicts many points you said before about getting the newer packages.

End users will have no lock file. Thus v2 or v3 would depend on their PHP version only.

> This should be removed or at least raised to 5.6, see http://php.net/supported-versions.php - even if Yii2 still runs with 5.4, you should not encourage people to use a completely unsupported version or install old versions. You already have a requirement for php >= 5.4.0.

Minimum PHP version is already raised for 2.1.

**Comment by schmunk42** [comment]
There are actually two `composer.json`s in yiisoft/yii2

- https://github.com/yiisoft/yii2/blob/master/composer.json
- https://github.com/yiisoft/yii2/blob/master/framework/composer.json

The first one is for `yii2-dev` or local development (testing/CI) with the repo, I think that was the use-case referred to or are there other tasks than that were you run `install` on the development repo.
While the second one is the one composer uses when installing `yiisoft/yii2`.

So @cebe confused me with his link :) Sorry, I thought it was in `yii2-app-basic` - where it actually would make sense (to a certain degree) - to create a lock compatible with `5.6` or `7.1`.
Isn't also `config.platform.php` only effective for the project's root `composer.json`?
But yes, I also see that it could be problematic to have *that setting*  in the template.

I won't see it as an error, when people running an unsupported outdated version of PHP would get an warning and would have to run `update`.

**Comment by curry684** [comment]
> If I'll do update while having PHP7 and push lock file then people with PHP 5.4 or even 5.6 won't be able to install Yii at all. So we'll have to generate lock file using PHP 5.4.

You can override platform dependencies in your composer.json. Symfony uses this itself to lock down to the lowest PHP version in its standard distribution.

I personally think that is a bad thing, but others agree with it. Both sides' points have merits.

**Comment by cebe** [comment]
Yeah, if we want to add composer.lock we need to add a platform setting and we need to include PHP 5.x to make the installation work on supported platforms.

This is bad for people on PHP 7.x versions, which could use newer libraries than they get as the default, while this would be the group we'd want to encourage to use new stuff.

**Comment by schmunk42** [comment]
If there'd be something like `composer create-project --update`, like described in https://github.com/composer/composer/issues/6282#issuecomment-288231959

You could create a `.lock` file (always for the current stable version of PHP) - without a setting platform setting in `.json` and tell the developer to use...

```
# PHP 7.1 (stable)
composer create-project

# PHP 5.6
composer create-project --update
```

...or add alternative lock files.

---

This becomes very relevant for testing, as we've already seen issues, just because of an underlying libs (ICU). It's even more relevant are PHP packages.

Currently this app-template installs most packages with [dev-master btw](https://travis-ci.org/yiisoft/yii2-app-basic/jobs/209163604#L186), which is cool on one hand, but tests are absolutely not reproducible at the moment.

**Comment by cebe** [comment]
> Currently this app-template installs most packages with dev-master btw, which is cool on one hand, but tests are absolutely not reproducible at the moment.

They do not, if you install a stable version. See https://github.com/yiisoft/yii2-app-basic/commit/5bb6386a5e421152a16f6afc8e254a5cd7423dee

**Comment by samdark** [comment]
So overall I don't think `.lock` should be added for templates. Introduces too many problems.

**Comment by schmunk42** [comment]
> They do not, if you install a stable version

That's why I added "at least in releases" on the very beginning ;)
And "tests are absolutely not reproducible at the moment." remains 😛 

Anyhow, I learned new things on how and in which environments people use the template.

**Comment by curry684** [comment]
> This is bad for people on PHP 7.x versions, which could use newer libraries than they get as the default, while this would be the group we'd want to encourage to use new stuff.

That's precisely the reason I dislike it [in Symfony Standard](https://github.com/symfony/symfony-standard/blob/master/composer.json), as I've seen multiple developers stumped as to why they couldn't use an external library as Composer refused to install the `>=7.0` dependency on their PHP 7.1.x dev machine.

Curiously, they [also include the lock](https://github.com/symfony/symfony-standard/blob/master/composer.lock) there. I dislike that even more, but fabpot and co must have their reasons.

**Comment by schmunk42** [comment]
@curry684 Sometimes it's required for external tools, like Scrutinizer ... i.e. the Yii2 Framework needs it AFAIK, because Scrutinizer does not allow the installation of a composer plugin.

The point is, that having a lock file should not affect your workflow. 

Let's put it the other way around,  `create-project` does the update by default, but then it would be nice to have

```
composer install-project
```

Will continue this at https://github.com/composer/composer/issues/6282
