### ISSUE TITLE
Please, add the namespaces for standard migrations

### ISSUE THREAD

**Issue by taita-wizard** [yiisoft/yii2-app-basic#116]
yii\rbac\migrations
yii\web\migrations

**Comment by taita-wizard** [comment]
Since 2.0.10 yii2 has namespaced migrations.

http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#modifying-migration-history

 So, if I want use this
```
return [
    'controllerMap' => [
        'migrate' => [
            'class' => 'yii\console\controllers\MigrateController',
            'migrationNamespaces' => [
                'app\migrations', 
               
            ],
        ],
    ],
```
I can't do that with standard yii2 migrations, and should install them separately

php yii migrate --migrationPath=@yii/rbac/migrations
php yii migrate --migrationPath=@yii/web/migrations

All you need to add nsamespace to this migrations.

**Comment by SilverFire** [comment]
Issue is related to yiisoft/yii2 repository.
There is a good one already: https://github.com/yiisoft/yii2/issues/13918

Thank you
