### ISSUE TITLE
Query Builder: join doesn't passes parameters

### ISSUE THREAD

**Issue by ElijahKaftanov** [yiisoft/yii2-app-basic#118]
```
$query = $query->leftJoin('DESIGNATIONS AS DESIGNATIONS2', [
                    'DESIGNATIONS2.DES_ID' => 'ART_DES_ID',
                    'AND DESIGNATIONS2.DES_LNG_ID' => ':langId'
                ],
                [':langId' => 16]
            );
```
### What's expected?
` LEFT JOIN `DESIGNATIONS` `DESIGNATIONS2` ON (`DESIGNATIONS2`.`DES_ID`='ART_DES_ID') AND (`AND DESIGNATIONS2`.`DES_LNG_ID`=16)`
### What do you get instead?
` LEFT JOIN `DESIGNATIONS` `DESIGNATIONS2` ON (`DESIGNATIONS2`.`DES_ID`='ART_DES_ID') AND (`AND DESIGNATIONS2`.`DES_LNG_ID`=':langId')`

**Comment by klimov-paul** [comment]
This is expected behavior. Use `yii\db\Expression` n case you wish to pass raw SQL, which bound parameter name is.

**Comment by cebe** [comment]
@ElijahKaftanov check the documentation of the condition parameter, array format does its own param binding internally, you do not need to use params for array syntax as it only works in string syntax.
