### ISSUE TITLE
gii create model error when change default db name

### ISSUE THREAD

**Issue by farhadi1552** [yiisoft/yii2-app-basic#124]
**What steps will reproduce the problem?**

## db.php 

return [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=localhost;dbname=mydbname',
    'username' => 'root',
    'password' => '',
    'charset' => 'utf8',
];

 
 **Additional info**
## my browser address :
 ... index.php?r=gii%2Fdefault%2Fview&id=model

## and throw exception  : 

Database Exception – yii\db\Exception
SQLSTATE[HY000] [1049] Unknown database 'yii2basic'
↵
Caused by: PDOException
SQLSTATE[HY000] [1049] Unknown database 'yii2basic'

in C:\xampp\htdocs\retrofit\vendor\yiisoft\yii2\db\Connection.php at line 630

### Additional info
| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| PHP version      | 7.0.13
| Operating system | windows 7

**Comment by Correcter** [comment]
Wen you generate the SomeModel in gii generator, you will be able to change your default "db" name to necessary by click under  "Database Connection ID" area and then generate it with other database. 
Hope will help u.
