### ISSUE TITLE
Replica/Master/Slave memory exhausted

### ISSUE THREAD

**Issue by iparianos** [yiisoft/yii2-app-basic#125]
### What steps will reproduce the problem?
I have setup Yii2.0 Basic App on a VM with 1 vCore, 1 GB Ram and on a separate VM I have set up the DB.
I've used a VM mysql replica and I've set up the db configurations of Yii to use as slave the replica VM and master the main mysql VM. But when I do that then I'm getting php fatal error memory exhausted. When I remove the Slave dsn etc and return back to default then works fine. The memory_limit of the app's VM is 512m since on 128m the app doesn't work. Mysql VMs have both 1 vCore and 1 GB Ram.

### What do you get instead?
PHP memory exhausted

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0
| Operating system | Centos

**Comment by cebe** [comment]
please report at https://github.com/yiisoft/yii2/issues and provide more details about your config, and which code causes the error.
