### ISSUE TITLE
Fixture for loading fake data with faker not work

### ISSUE THREAD

**Issue by mortezakarimi** [yiisoft/yii2-app-basic#128]
### What steps will reproduce the problem?
When i create fixture for testing database table with fake data
and I run `php yii fixture/load` and everything okay but don't load any row in database
### What's expected?
faker data don't load in database
### What do you get instead?
Runned tests

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 7.0.18
| Operating system | Ubuntu-16.04.1

**Comment by SilverFire** [comment]
Failed to reproduce.

Tried the following steps:

1. Install app
```bash
composer create-project --dev --prefer-dist yiisoft/yii2-app-basic:@dev basic
cd basic
```

2. Adjust DB connection credentials in `config/db.php`

3. Uncomment `FixtureController` in `controllerMap` and set namespaces according to your app:

```php
    'controllerMap' => [
        'fixture' => [ // Fixture generation command line.
            'class' => 'yii\faker\FixtureController',
            'namespace' => 'app\tests\unit\fixtures',
            'templatePath' => '@app/tests/unit/templates/fixtures',
            'fixtureDataPath' => '@app/tests/unit/fixtures/data',
        ],
    ],
```

4. I have table `item` in my database with columns `id`, `name`, `category_id`. I create fixture template:
```bash
mkdir -p unit/templates/fixtures
vim unit/templates/fixtures/Item.php
```

```php
<?php                                                                                                                                                                                                                                          

return [
    'name' => $faker->name,
    'category_id' => $faker->randomDigitNotNull
];
```

5. I generate model and data:
```bash
./yii gii/model --tableName=item --modelClass=Item
mkdir -p tests/unit/fixtures
./yii fixture/generate Item
```

6. I create a fixture class `tests/unit/fixtures/ItemFixture.php`
```bash
<?php                                                                                                                  

namespace app\tests\unit\fixtures;

use yii\test\ActiveFixture;

class ItemFixture extends ActiveFixture
{
    public $modelClass = \app\models\Item::class;
}
```

7. I load fixtures into the DB:
```bash
./yii fixture/load Item
```
