### ISSUE TITLE
Add "aliaces" section in config/test.php

### ISSUE THREAD

**Issue by Matvik** [yiisoft/yii2-app-basic#130]
There is new section "aliaces" in main config of the last yii 2 version:
```php
'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
```
 
and we have "bower-asset" and "npm-asset" folders instead "bower" and "npm" in vendor-folder.
But it is missing in test config, so an error occures when trying run tests.
It is goot to have this section in test config by default.

**Comment by samdark** [comment]
@Matvik would you like to do a pull request?
