### ISSUE TITLE
Add Vagrant and Docker support

### ISSUE THREAD

**Issue by dabagab** [yiisoft/yii2-app-basic#133]
It will be great if the Yii2-app-basic can get the same Vagrant scripts which can be found in the advanced template too and extends with Docker scripts too.

### What's expected?
This repository contains vagrant and docker running scripts.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | Not important
| PHP version      | Not important
| Operating system | Ubuntu 16.04 LTS

**Comment by cgrs** [comment]
Done on this PR: #161
