### ISSUE TITLE
a subtle bug in the vendor/bower directory

### ISSUE THREAD

**Issue by medmin** [yiisoft/yii2-app-basic#136]
### What steps will reproduce the problem?
install different js libs
### What's expected?
to install them successfully
### What do you get instead?

sometimes they need to be installed in a vendor/bower dir
sometimes they need to be installed in a vender/bower-asset dir

Whether you get this error, it depends on the first time when you create the yii-app-basic app. 
If the first time, you get a vendor/bower, most js libs would be  fine. And sometimes, somehow, you get a vendor/bower-asset dir, and you need to modify some code. I can modify Line 461 in the file of vendor/yiisoft/yii2/base/Application.php and the error goes away.

/**
454      * Sets the directory that stores vendor files.
455      * @param string $path the directory that stores vendor files.
456      */
457     public function setVendorPath($path)
458     {
459         $this->_vendorPath = Yii::getAlias($path);
460         Yii::setAlias('@vendor', $this->_vendorPath);
461         Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
462         Yii::setAlias('@npm', $this->_vendorPath . DIRECTORY_SEPARATOR . 'npm');
463     }

The  original code of Line 461 is 'bower' and if the error messages tell me that it needs to be installed in the vendor/bower-asset, you just change it to the 'bower-asset'. 

Anyways, I cannot predict when a js lib needs to be installed in vendor/bower and when in vendor/bower-asset. Although i can easily get the error corrected, it's still annoying.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  Yii2
| PHP version      |  7.0.X
| Operating system | Linux or Windows

**Comment by samdark** [comment]
Are you installing libs manually?

**Comment by medmin** [comment]
@samdark  No. I add the js lib information in the composer.json file and execute "composer install" in console.  

I do not use "composer require".

**Comment by samdark** [comment]
What's in your composer.json?

**Comment by medmin** [comment]
"require": {
        "php": ">=5.4.0",
         // other libs
        "bower-asset/izitoast": "^1.1"

**Comment by medmin** [comment]
"require": {
         "php": ">=5.4.0",
         // other libs 
         "bower-asset/izitoast": "^1.1"
    },

**Comment by samdark** [comment]
Not only require section is interesting.

**Comment by samdark** [comment]
- https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L69
- https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L64
- https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L33

**Comment by samdark** [comment]
Anyway, closing the issue since it's likely configuration mistake.
