### ISSUE TITLE
template code fails after install

### ISSUE THREAD

**Issue by wehe64** [yiisoft/yii2-app-basic#138]
### What steps will reproduce the problem?
composer create-project --prefer-dist yiisoft/yii2-app-basic failcase
cd failcase/
php -S localhost:8080 -t web/
open http://localhost:8080

### What's expected?
see demo page
### What do you get instead?
Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /home/wehe/Development/tests/PHP/yiitst/failcase/vendor/bower/jquery/dist

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | PHP 7.1.8 
| Operating system | 4.12.8-2-MANJARO x86_64

thx & kind regards, weHe

**Comment by samdark** [comment]
Please re-check installation instructions.

**Comment by cebe** [comment]
works for me:

```
$ composer create-project --prefer-dist yiisoft/yii2-app-basic failcase
Installing yiisoft/yii2-app-basic (2.0.12)
  - Installing yiisoft/yii2-app-basic (2.0.12): Downloading (100%)         
Created project in failcase
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 59 installs, 0 updates, 0 removals     
  - Installing yiisoft/yii2-composer (2.0.5): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.8): Loading from cache
  - Installing bower-asset/jquery (2.2.4): Loading from cache
  - Installing bower-asset/yii2-pjax (v2.0.6): Loading from cache
  - Installing bower-asset/punycode (v1.3.2): Loading from cache
  - Installing cebe/markdown (1.1.2): Loading from cache
  - Installing ezyang/htmlpurifier (v4.9.3): Loading from cache
  - Installing bower-asset/jquery.inputmask (3.3.8): Downloading (100%)         
  - Installing yiisoft/yii2 (2.0.12): Loading from cache
  - Installing yiisoft/yii2-swiftmailer (2.0.7): Downloading (100%)         
  - Installing bower-asset/bootstrap (v3.3.7): Loading from cache
  - Installing yiisoft/yii2-bootstrap (2.0.6): Loading from cache
  - Installing yiisoft/yii2-debug (2.0.9): Loading from cache
  - Installing bower-asset/typeahead.js (v0.11.1): Loading from cache
  - Installing phpspec/php-diff (v1.1.0): Loading from cache
  - Installing yiisoft/yii2-gii (2.0.5): Loading from cache
  - Installing fzaninotto/faker (v1.7.1): Downloading (100%)         
  - Installing yiisoft/yii2-faker (2.0.3): Downloading (100%)         
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.8): Downloading (100%)         
  - Installing symfony/polyfill-mbstring (v1.5.0): Loading from cache
  - Installing symfony/console (v3.3.8): Downloading (100%)         
  - Installing stecman/symfony-console-completion (0.7.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/recursion-context (2.0.0): Downloading (100%)         
  - Installing sebastian/exporter (2.0.0): Downloading (100%)         
  - Installing sebastian/comparator (1.2.4): Loading from cache
  - Installing behat/gherkin (v4.4.5): Loading from cache
  - Installing symfony/dom-crawler (v3.3.8): Downloading (100%)         
  - Installing symfony/css-selector (v3.3.8): Downloading (100%)         
  - Installing symfony/browser-kit (v3.3.8): Downloading (100%)         
  - Installing symfony/yaml (v3.3.8): Downloading (100%)         
  - Installing symfony/event-dispatcher (v3.3.8): Downloading (100%)         
  - Installing symfony/finder (v3.3.8): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (3.4.4): Downloading (100%)         
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)         
  - Installing phpunit/php-token-stream (1.4.11): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing sebastian/environment (2.0.0): Loading from cache
  - Installing phpunit/php-code-coverage (4.0.8): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Downloading (100%)         
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.3.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-docblock (3.2.2): Downloading (100%)         
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing myclabs/deep-copy (1.6.1): Loading from cache
  - Installing sebastian/global-state (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (2.0.1): Downloading (100%)         
  - Installing phpunit/phpunit (5.7.21): Downloading (100%)         
  - Installing codeception/base (2.3.5): Downloading (100%)         
  - Installing codeception/verify (0.3.3): Loading from cache
  - Installing codeception/specify (0.4.6): Loading from cache
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
symfony/browser-kit suggests installing symfony/process ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
codeception/base suggests installing flow/jsonpath (For using JSONPath in REST module)
codeception/base suggests installing phpseclib/phpseclib (for SFTP option in FTP Module)
codeception/base suggests installing league/factory-muffin (For DataFactory module)
codeception/base suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
Writing lock file
Generating autoload files
> yii\composer\Installer::postCreateProject
chmod('runtime', 0777)...done.
chmod('web/assets', 0777)...done.
chmod('yii', 0755)...done.
$ cd failcase/
$ php -S localhost:8080 -t web/
PHP 5.6.30-0+deb8u1 Development Server started at Fri Sep  1 12:53:20 2017
Listening on http://localhost:8080
Document root is /tmp/wtf/failcase/web
Press Ctrl-C to quit.
[Fri Sep  1 12:53:23 2017] ::1:60974 [200]: /
[Fri Sep  1 12:53:23 2017] ::1:60975 [200]: /assets/5d97333b/css/bootstrap.css
[Fri Sep  1 12:53:23 2017] ::1:60977 [200]: /assets/3faceeb/jquery.js
[Fri Sep  1 12:53:23 2017] ::1:60976 [200]: /css/site.css
[Fri Sep  1 12:53:23 2017] ::1:60979 [200]: /assets/5d97333b/js/bootstrap.js
[Fri Sep  1 12:53:23 2017] ::1:60978 [200]: /assets/1408aaa/yii.js
[Fri Sep  1 12:53:23 2017] ::1:60980 [200]: /index.php?r=debug%2Fdefault%2Ftoolbar&tag=59a93c2360a60
[Fri Sep  1 12:53:23 2017] ::1:60981 [200]: /favicon.ico
```

```
$ composer --version
Composer version 1.4.1 2017-03-10 09:29:45
$ composer global show |grep fxp
fxp/composer-asset-plugin             v1.3.1 NPM/Bower Dependency Manager for Composer
```

make sure you have latest version of composer and asset plugin installed.

**Comment by wehe64** [comment]
thx for the quick response! 

[wehe@wernix yiitst]$ composer self-update
You are already using composer version 1.5.1 (stable channel).
[wehe@wernix yiitst]$ composer create-project --prefer-dist yiisoft/yii2-app-basic failcase
Installing yiisoft/yii2-app-basic (2.0.12)
  - Installing yiisoft/yii2-app-basic (2.0.12): Loading from cache
Created project in failcase
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 63 installs, 0 updates, 0 removals     
  - Installing yiisoft/yii2-composer (2.0.5): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.8): Loading from cache
  - Installing bower-asset/jquery (2.2.4): Loading from cache
  - Installing bower-asset/yii2-pjax (v2.0.6): Loading from cache
  - Installing bower-asset/punycode (v1.3.2): Loading from cache
  - Installing cebe/markdown (1.1.2): Loading from cache
  - Installing ezyang/htmlpurifier (v4.9.3): Loading from cache
  - Installing bower-asset/jquery.inputmask (3.3.8): Loading from cache
  - Installing yiisoft/yii2 (2.0.12): Loading from cache
  - Installing yiisoft/yii2-swiftmailer (2.0.7): Loading from cache
  - Installing bower-asset/bootstrap (v3.3.7): Loading from cache
  - Installing yiisoft/yii2-bootstrap (2.0.6): Loading from cache
  - Installing yiisoft/yii2-debug (2.0.9): Loading from cache
  - Installing bower-asset/typeahead.js (v0.11.1): Loading from cache
  - Installing phpspec/php-diff (v1.1.0): Loading from cache
  - Installing yiisoft/yii2-gii (2.0.5): Loading from cache
  - Installing fzaninotto/faker (v1.7.1): Loading from cache
  - Installing yiisoft/yii2-faker (2.0.3): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.8): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.5.0): Loading from cache
  - Installing symfony/console (v3.3.8): Loading from cache
  - Installing stecman/symfony-console-completion (0.7.0): Loading from cache
  - Installing sebastian/diff (1.4.3): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/comparator (2.0.0): Loading from cache
  - Installing behat/gherkin (v4.4.5): Loading from cache
  - Installing symfony/dom-crawler (v3.3.8): Loading from cache
  - Installing symfony/css-selector (v3.3.8): Loading from cache
  - Installing symfony/browser-kit (v3.3.8): Loading from cache
  - Installing symfony/yaml (v3.3.8): Loading from cache
  - Installing symfony/event-dispatcher (v3.3.8): Loading from cache
  - Installing symfony/finder (v3.3.8): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (4.0.4): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.1): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.2): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.2.3): Loading from cache
  - Installing phpspec/prophecy (v1.7.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.6.1): Loading from cache
  - Installing phpunit/phpunit (6.2.4): Loading from cache
  - Installing codeception/base (2.3.5): Loading from cache
  - Installing codeception/verify (0.3.3): Loading from cache
  - Installing codeception/specify (0.4.6): Loading from cache
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
symfony/browser-kit suggests installing symfony/process ()
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
codeception/base suggests installing flow/jsonpath (For using JSONPath in REST module)
codeception/base suggests installing phpseclib/phpseclib (for SFTP option in FTP Module)
codeception/base suggests installing league/factory-muffin (For DataFactory module)
codeception/base suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
Writing lock file
Generating autoload files
> yii\composer\Installer::postCreateProject
chmod('runtime', 0777)...done.
chmod('web/assets', 0777)...done.
chmod('yii', 0755)...done.
[wehe@wernix yiitst]$ cd failcase/
[wehe@wernix failcase]$ php -S localhost:8080 -t web/
PHP 7.1.8 Development Server started at Fri Sep  1 13:01:50 2017
Listening on http://localhost:8080
Document root is /home/wehe/Development/tests/PHP/yiitst/failcase/web
Press Ctrl-C to quit.
[Fri Sep  1 13:01:58 2017] ::1:59594 [500]: /
[Fri Sep  1 13:01:58 2017] ::1:59596 [200]: /index.php?r=debug%2Fdefault%2Ftoolbar&tag=59a93e260f4ef
[Fri Sep  1 13:01:58 2017] ::1:59598 [200]: /favicon.ico

what now? THX/weHe

**Comment by wehe64** [comment]
fyi, same after "composer clear-cache" (and re-do from start). hth / w

**Comment by cebe** [comment]
`composer global require "fxp/composer-asset-plugin:^1.3.1"`

**Comment by wehe64** [comment]
that did the job - I hereby declare you my hero of the day!
THX a lot / weHe
