### ISSUE TITLE
Many stray megabytes of .git files in vendor

### ISSUE THREAD

**Issue by jimgwhit** [yiisoft/yii2-app-basic#142]
### Additional info after the composer update I had .git files all over the vendor folder, what is the deal?  I have been updating laravel for years, then running a composer update, and never got tons of stray .git files. The stray .git files is where the stray Megabytes derived from.

Side question                   where is app.log now the update on https://github.com/yiisoft/yii2-app-basic/tree/master/runtime  only has .gitignore now, prior it had logs/app.log, I had used composer to install first time.

My original install prior to this mess, all went smooth.

And what is the world is:
```
The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option
```
Vendor folder prior to update = 31.7 MB
I deleted all stray .git files.
Vendor folder after update = 71.5 MB

With the removal of the stray git files, why is the before update so much
smaller compared with the after update size. And that's after removing the .git files.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13-dev
| PHP version      | 7.1.7-0
| Operating system | Windows 10

**Comment by schmunk42** [comment]
If you do not want git repositories in vendor you need to install your packages with

    composer install --prefer-dist

A vanilla installation with the above command contains a `vendor` folder with `78M` which is `17M` zipped.

> Side question where is app.log now the update on https://github.com/yiisoft/yii2-app-basic/tree/master/runtime only has .gitignore now, prior it had logs/app.log, I had used composer to install first time.

The last change for this folder dates back to 2013: https://github.com/yiisoft/yii2-app-basic/commits/master/runtime - `logs/app.log` was never part of it.

> And what is the world is: `The "extra.asset-installer-paths" option is deprecated, use the "config.fxp-asset.installer-paths" option`

It tells you that you should update your composer config to a new syntax. It does not affect you directly at the moment, but it will be needed in a future version.
