### ISSUE TITLE
Trailing hypen in route - yii\base\ViewNotFoundException

### ISSUE THREAD

**Issue by corpsepk** [yiisoft/yii2-app-basic#159]
### What steps will reproduce the problem?
1. install default yii2-app-basic
2. php yii serve
3.  go to http://localhost:8080/index.php?r=site-%2Fcontact
*trailing hypen after `site`

### What's expected?
`/site/contact` page or at least `404 Not Found`

### What do you get instead?
View not Found – `yii\base\ViewNotFoundException`

### Additional info
- Simple falling test - https://github.com/corpsepk/yii2-app-basic/commit/91b1af93a4679f0695281b7e275f3813a486a040
- That exception also thrown in yii2-app-advanced
- works only with `UrlManager->enableStrictParsing = false` (by default)

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| PHP version      | 7.1.5
| Operating system | Debian 8

**Comment by samdark** [comment]
Why should it work with added `-`?

**Comment by corpsepk** [comment]
I think `yii\base\ViewNotFoundException` not expected here...
http://yiiframework.ru/site-/login

**Comment by rob006** [comment]
Probably duplicate of https://github.com/yiisoft/yii2/issues/14903

**Comment by samdark** [comment]
Ah. Right. I'll get to it.
