### ISSUE TITLE
to fix acceptance test СontactCest.php in basic There, with a successful log error is out.

### ISSUE THREAD

**Issue by kopyrin** [yiisoft/yii2-app-basic#164]
### What steps will reproduce the problem?
codeception run  acceptance
### What do you get instead?
error in test СontactCest.php

### Additional info

| Q                          | A
| ------------------- | ---
| Yii vesion              | 2.0.13.1
| PHP version          | 5.6
| Operating system | Windows 7

**Comment by samdark** [comment]
https://github.com/Codeception/Codeception/issues/4759
