### ISSUE TITLE
Vagrantfile contains wrong filepath to the vagrant config file.

### ISSUE THREAD

**Issue by botalaszlo** [yiisoft/yii2-app-basic#165]
### What steps will reproduce the problem?
Running the `vagrant up` command
### What's expected?
It is going to run without any error.
### What do you get instead?
I got a simple error: 
> Message: Errno::ENOENT: No such file or directory @ rb_sysopen - ./vagrant/config/vagrant-local.example.yml

Problem is the following. In the Vagrantfile we have the wrong filename, or the linked filename was not modified after the Vagrantfile modification.

Vagrantfile has the following filepath: ` example: './vagrant/config/vagrant-local.example.yml'`
While in the app-basic directory there is this version:  `example: './vagrant/config/vagrant-local-example.yml'`
The difference only that in vagrantfile there is **dot** instead of **dash** ---> `local.example`, `local-example`.

So you have to update only the filename in the VagrantFile or under the /vagrant/config directory.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.x
| PHP version      | 7.0
| Operating system | Fedora 27

**Comment by samdark** [comment]
Fixed, thanks.
