### ISSUE TITLE
Failed to run ./yii migrate up prod server

### ISSUE THREAD

**Issue by solucionti** [yiisoft/yii2-app-basic#166]
### What steps will reproduce the problem?
1- Clone site.
2 - Run ./init and select production mode.
3 - Run ./yii migrate up
### What do you get instead?
Execute migrations, similar to what happens in local servers and QA

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| PHP version      | 7.1
| Operating system | Centos

The situation is rare in my other two Dreamhost servers and localhost works without problems, but in my production server it only throws an empty line. Probe granting the execution permits and nevertheless the problem persists

Attachment captures.
Thank you
![camilo camilo -sites-sitios-motelchile-v2 desarrollo_070](https://user-images.githubusercontent.com/9874555/35487133-030e055e-0457-11e8-9686-666e650ddf16.png)

Attachment captures.
Thank you

**Comment by samdark** [comment]
Likely symlink problem.

**Comment by schmunk42** [comment]
You might try also:
- `which yii` to find out what's really called
- `yii help`
