### ISSUE TITLE
test [Error] Class 'PHPUnit_Framework_Assert' not found

### ISSUE THREAD

**Issue by biaoqianwo** [yiisoft/yii2-app-basic#172]
When I run `./vendor/bin/codecept run` ,
There are many errors for unit test,likely '[Error] Class 'PHPUnit_Framework_Assert' not found'

Just because the  'codeception/verify' version is too old:
```
"require-dev": {
         //...  
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
```
PHPUnit_Framework_Assert is replace by PHPUnit\Framework\Assert
```
"require-dev": {
         //...  
        "codeception/verify": "~1.0.0",
        "codeception/specify": "~0.4.6"
    },
```
**Pls NOTE: Maybe codeception/specify composer.json has an error. So cannot update to v1.0.**
So you can upgrade the composer.json
Thanks.

**Comment by ricpelo** [comment]
This works OK for me:

```php
"require-dev": {
     //...  
    "codeception/verify": "~1.0.0",
    "codeception/specify": "~1.0.0"
},
```
