### ISSUE TITLE
Database Exception – yii\db\Exception could not find driver

### ISSUE THREAD

**Issue by syaifulrmdhn** [yiisoft/yii2-app-basic#174]
i have a problem...

DB connection: could not find driver
i use PostgreSQL for my database
this is my db.php

`<?php 
return ['class' => 'yii\db\Connection',
    'dsn' => 'pgsql:host=127.0.0.1;dbname=myDB',
    'username' => 'postgres',
    'password' => '',
    'charset' => 'utf8',
];`

I use laragon
how to fix it?

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0
| PHP version      | 7.1.12
| Operating system | Win 10

**Comment by larryli** [comment]
Please run:
```
php requirements.php
```

**Comment by syaifulrmdhn** [comment]
> PDO PostgreSQL extension: WARNING!!!
Required by: All DB-related classes
Memo: Required for PostgreSQL database.

**Comment by shinuantony1995** [comment]
i have the same problem while using yii2 
Database Exception – yii\db\Exception
could not find driver
↵
Caused by: PDOException
 how to correct this error

**Comment by smelike** [comment]
> i have the same problem while using yii2
> Database Exception – yii\db\Exception
> could not find driver
> ↵
> Caused by: PDOException
> how to correct this error
go the root directory of the project, and  run `php requirements.php`

**Comment by Narendra1995-bng** [comment]
i have the same problem i am unable to connect to postgresSQL , kindly reply what should i do, what extension to enable and disable

**Comment by bizley** [comment]
Please use [forum](https://forum.yiiframework.com/) for that kind of issues.
