### ISSUE TITLE
Vagrant provisioning for PHP should be updated

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2-app-basic#176]
Currently installed version is 7.0, current stable 7.x is PHP 7.2.3.

From what I see, this will impact following:

- Installed software
    - php7.0-curl
    - php7.0-cli
    - php7.0-intl
    - php7.0-mysqlnd
    - php7.0-gd
    - php7.0-fpm
    - php7.0-mbstring
    - php7.0-xml
- FPM configuration
- Xdebug configuration
- Restart webstack procedure
- nGINX configuration

**Comment by Deele** [comment]
Just installed current version and right at the end, provisoner displays an error:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
carcompare:
  Problem 1
    - symfony/browser-kit v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
    - symfony/browser-kit v4.0.4 requires php ^7.1.3 -> your PHP version (7.0.25) does not satisfy that requirement.
    - Installation request for symfony/browser-kit v4.0.4 -> satisfiable by symfony/browser-kit[v4.0.4].
```

**Comment by cgsmith** [comment]
Just built a vagrant box off the yii2-basic section and get 7.0.28 - 1 minor version behind.
```
vagrant@yii2-basic:/app/web$ php --version
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
```

**Comment by ruslanzelinskyy** [comment]
@samdark Why not start to use docker instead?
richarvey/nginx-php-fpm fits perfectly.

Or there is some problems described in some topic?
