### ISSUE TITLE
Vagrant up did not delete `default` from nginx

### ISSUE THREAD

**Issue by cgsmith** [yiisoft/yii2-app-basic#177]
### What steps will reproduce the problem?
1. `git clone git@github.com:yiisoft/yii2-app-basic.git`
1. `cd yii2-app-basic`
1. Change `vagrant/config/vagrant-local.yml` with Personal Access Token
1. `vagrant up`
1. Visit http://yii2basic.dev or http://yii2basic/

### What's expected?
Website should show Yii2 Basic template page when going to http://yii2basic.dev 

### What do you get instead?
Redirect to https://yii2basic.dev happens. No application is shown. When trying http://yii2basic/ the default nginx config page loads.

I needed to run `sudo rm /etc/nginx/sites-enabled/default && sudo service nginx restart` to get it to show a page. The redirect still happens on yii2basic.dev to https:// which is an invalid configuration

### Additional info
I have to remove the `default` config under `/var/nginx/sites-enabled/default` for the VM to work correctly.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15
| PHP version      | 7.0.28
| Operating system | Ubuntu 16.04

**Comment by samdark** [comment]
https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/

**Comment by cgsmith** [comment]
I remember reading about this. Thanks for the reminder.
