### ISSUE TITLE
Debugbar don't appear

### ISSUE THREAD

**Issue by calcio** [yiisoft/yii2-app-basic#186]
### What steps will reproduce the problem?
Even an new installation using the documentation like:
```
Install with Docker

Update your vendor packages

docker-compose run --rm php composer update --prefer-dist

Run the installation triggers (creating cookie validation code)

docker-compose run --rm php composer install    

Start the container

docker-compose up -d

You can then access the application through the following URL:

http://127.0.0.1:8000
```
The **index.php** file it's configured to DEV and the **config/web.php** it's configured using * to allow any IP

### What's expected?
It expected the debugbar appear when run the project 
### What do you get instead?
I can't see the debugbar. When I inspect the main page I got an **404 status** at _http://127.0.0.1:8080/index.php?r=debug%2Fdefault%2Ftoolbar&tag=5b58d1b2d7da7_ url.
The response is **Not Found (#404): Unable to find debug data tagged with '5b58d1b2d7da7'.**

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |~2.0.14
| PHP version      |7.1.17
| Operating system |Linux Mint

**Comment by samdark** [comment]
How do you install it with docker exactly?

**Comment by calcio** [comment]
So, I cloned it and ran the Install with Docker section.

**Comment by samdark** [comment]
Which Docker section?

**Comment by calcio** [comment]
In this link: [https://github.com/yiisoft/yii2-app-basic#install-with-docker](https://github.com/yiisoft/yii2-app-basic#install-with-docker) in READEME.MD

**Comment by lgnap** [comment]
Same error, I'm investigating it

**Comment by lgnap** [comment]
Ok, first investigation done: issue with rights.

A quick (DIRTY) fix is:
 - jump into docker with `docker-compose run php bash`
 - go to the right folder `cd /app/runtime/debug/`
 - and adapt rights: `chmod o+rwx .`

A better solution is in progress and will come asap (something like change uid of www-data user).

**Comment by calcio** [comment]
> Ok, first investigation done: issue with rights.
> 
> > A quick (DIRTY) fix is:
> > 
> > * jump into docker with `docker-compose run php bash`
> > * go to the right folder `cd /app/runtime/debug/`
> > * and adapt rights: `chmod o+rwx .`
> 
> The good fix is:
> 
>     * define environment var `PHP_USER_ID` same than your local UID _often 1000 but not always_ into your docker-compose.yml (according to [the doc](https://github.com/yiisoft/yii2-docker#configuration))
> 
>     * clean runtime folder
> 
> 
> Enjoy +1

Yeah I got it. I force it many times and works. Thanks!
