### ISSUE TITLE
Is the Imagick method not cleaned?

### ISSUE THREAD

**Issue by Sun-FreePort** [yiisoft/yii2-app-basic#189]
### Code

I find this code, so i want to know, the Imagick occupy memory is cleaned?
(not find anything of `$image->clear()` / `$image->destory()`)

```php
// \yii\captcha\CaptchaAction::renderImageByImagick
    protected function renderImageByImagick($code)
    {
        // ... some code
        $image = new Imagick();
        $image->newImage($this->width, $this->height, $backColor);
        // ... some code
        $image->setImageFormat('png');
        return $image->getImageBlob();
    }
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.15.1
| PHP version      | 7.28
| Operating system | Win

**Comment by schmunk42** [comment]
I think this is done at the end of the request by PHP.

**Comment by Sun-FreePort** [comment]
Thank.
you are right, I can't get the answer on Yii2.
