### ISSUE TITLE
Gii Return 403 on Docker Container

### ISSUE THREAD

**Issue by deshario** [yiisoft/yii2-app-basic#192]
After I run yii2 on docker ... i gonna use gii but it seems like not working ... it return
 Forbidden (#403) => You are not allowed to access this page. but webapp is working well.

### Docker
![yii2 docker](https://user-images.githubusercontent.com/11426727/52260717-8c0cfb80-2959-11e9-8ce1-9d3931cb9c98.png)

### Config
![gii config](https://user-images.githubusercontent.com/11426727/52260905-2a995c80-295a-11e9-9a47-0374f1a8db51.png)

### APP
![gii error](https://user-images.githubusercontent.com/11426727/52261016-819f3180-295a-11e9-9af9-049a49752714.png)

APP URL : http://localhost:8010/
GII URL : http://localhost:8010/gii

Is there anything that missing from me ...

**Comment by machour** [comment]
You need to allow your host IP in the configuration file for the gii module. 
Since this is a docker setup, it won't be 127.0.0.1 but something else. 
`<?php var_dump($_SERVER['REMOTE_ADDR']); ?>` Should tell you what it is.

**Comment by deshario** [comment]
@machour Thanks. `REMOTE_ADDR` works.

**Comment by o251298** [comment]
Вы лучший)
