### ISSUE TITLE
Pull the environment variable from the command line 

### ISSUE THREAD

**Issue by codeChap** [yiisoft/yii2-app-basic#195]
https://github.com/yiisoft/yii2-app-basic/blob/603f13964b875ac98406845467fc0ecfc592d11b/yii#L12

Would it not be better to change this line to something like:
defined('YII_ENV') or define('YII_ENV', (getenv('YII_ENV') ? : 'dev'));

That way you can pass the variable via the command line:
YII_ENV=prod php yii do/whatEver

**Comment by samdark** [comment]
Could be done, yes.

**Comment by larryli** [comment]
@codeChap I use the [janisto/yii2-environment](https://github.com/janisto/yii2-environment) extension in my projects.

Add `set $env prod;` for the nginx configure.

On the console just:
```shell
YII_ENV=prod php yii
```

**Comment by samdark** [comment]
Decided not to do it by default. Easy to achieve if needed.
