### ISSUE TITLE
functional tests are failing with stability set to dev

### ISSUE THREAD

**Issue by pkestefran** [yiisoft/yii2-app-basic#198]
### What steps will reproduce the problem?

1. run `composer create-project --prefer-dist --stability=dev yiisoft/yii2-app-basic basic`
2. change directory `cd basic`
3. edit db details in `config\db.php` and `config\test_db.php` (if needed)
4. run `vendor/bin/codecept run`

### What's expected?
All tests should pass.
### What do you get instead?
All functional tests failed with following message:

`[ReflectionException] Property Symfony\Component\BrowserKit\Client::$maxRedirects does not exist`

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.17-dev
| PHP version      | 7.2.10
| Operating system | Windows 10 & CentOS 7.6.1810

**Comment by Infoto** [comment]
Just add `"symfony/browser-kit": ">=2.7 <=4.2.4"` in your dev dependencies. It seems that  `maxRedirects` is now property of the parent class of Client, thus the ReflectionProperty can't find it in the Client class.

**Comment by Naktibalda** [comment]
This issue was fixed in `codeception/codeception` [3.0.3](https://github.com/Codeception/Codeception/commit/7a3c911c60d48f3f38d33a53ba9e1dd5fc456492#diff-fde80abc0dc33fc4bca3b43f571f8934)
But for some reason packagist doesn't see a corresponding version of `codeception/base`.
