### ISSUE TITLE
Error during CLI migration not returning exitcode 1 as expected

### ISSUE THREAD

**Issue by rumours86** [yiisoft/yii2-app-basic#202]
### What steps will reproduce the problem?
> php yii_test migrate --interactive=0

https://github.com/yiisoft/yii2-app-basic/issues/180

**Comment by rumours86** [comment]
Yii Migration Tool (based on Yii v2.0.17)

**Comment by machour** [comment]
Closing this as #180 is much more verbose & clear ..
