### ISSUE TITLE
Deprecated use of Symfony/EventDispatcher in tests

### ISSUE THREAD

**Issue by santilin** [yiisoft/yii2-app-basic#207]
### What steps will reproduce the problem?

Install yii2-app-basic from scratch and run 
  vendor/codecept/run

### What's expected?

Tests are run without deprecations.

### What do you get instead?

Codeception PHP Testing Framework v2.3.9
Powered by PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Functional Tests (10) -----------------------------------------------------------------------------------------------------------------
E ContactFormCest: Open contact page 
E ContactFormCest: Submit empty form 
E ContactFormCest: Submit form with incorrect email 
E ContactFormCest: Submit form successfully 
E LoginFormCest: Open login page 
E LoginFormCest: Internal login by id 
E LoginFormCest: Internal login by instance 
E LoginFormCest: Login with empty credentials 
E LoginFormCest: Login with wrong credentials 
E LoginFormCest: Login successfully 
---------------------------------------------------------------------------------------------------------------------------------------
3x DEPRECATION: Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead. /home/santilin/devel/yii2base/apps/tests/basic/vendor/symfony/event-dispatcher/EventDispatcher.php:58 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | git
| PHP version      | 7.3
| Operating system | linux

**Comment by samdark** [comment]
Yes but we cannot upgrade PHPUnit since older PHP version is supported.

**Comment by faizanktk** [comment]
@samdark any update about this issue?

**Comment by samdark** [comment]
Is it still an issue? Codeception was bumped to ^4.0 since then.
