### ISSUE TITLE
form get pretty url

### ISSUE THREAD

**Issue by MichalNemec** [yiisoft/yii2-app-basic#208]
### What steps will reproduce the problem?

1. download basic app
2. turn ON pretty url
3. create basic form with one input and with: GET, url '/search'
4. create in url manager url 'search/<query> => 'search/index'

### What's expected?
expected url 'http://localhost/search/inputdata

### What do you get instead?
url 'http://localhost/search?query=inputdata

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.20
| PHP version      | 7.2.18
| Operating system | win10

**Comment by Thoulah** [comment]
`'search/<query:.*?>' => 'search/index'`
