### ISSUE TITLE
ERROR: Cannot create container for service php: invalid bind mount spec "/root/.composer-docker/cache:/root/.composer/cache:delegated": invalid mode: delegated

### ISSUE THREAD

**Issue by dqshll** [yiisoft/yii2-app-basic#209]
### What steps will reproduce the problem?
I try to install with docker on my server CentOS 7.6.1810 with docker and docker-compose already install and I login to docker hub ok.
then:
I git clone https://github.com/yiisoft/yii2-app-basic
and cd to the folder and try to follow the ReadMe step "Install with Docker":
docker-compose run --rm php composer update --prefer-dist
### What's expected?
I expected "Update your vendor packages" success info
### What do you get instead?
ERROR: Cannot create container for service php: invalid bind mount spec "/root/.composer-docker/cache:/root/.composer/cache:delegated": invalid mode: delegated

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
@schmunk42 would you please check it?

**Comment by schmunk42** [comment]
@dqshll Which docker and docker-compose version are you using? See also **NOTES** under https://github.com/yiisoft/yii2-app-basic#install-with-docker

**Comment by dqshll** [comment]
thanks @schmunk42 it's because my docker version is too low. Sorry for bothering you guys.

**Comment by dqshll** [comment]
Hi, Munk
   Thanks for your help. I have a further question about yii2 with docker.
   I can run this template with 8000 port and now I need to run app with https.
   I noticed there is a default ssl conf file at /etc/apache2/sites-avalable/default-ssl.conf in the container “yiisoftware/yii2-php:7.1-apache”
   Is it can be used to run https? Any other configuration should be done in Yii project?
br, DQ
On 06/25/2019 14:59，Tobias Munk<notifications@github.com> wrote：

@dqshll Which docker and docker-compose version are you using? See also NOTES under https://github.com/yiisoft/yii2-app-basic#install-with-docker

**Comment by schmunk42** [comment]
The ssl conf is from the PHP base-image, I think. 
We did not prepare the image to run with SSL enabled, although this is possible with a self-signed cert for testing; I'd recommend to do the SSL-Termination with a proxy like `jwilder/nginx` or `traefik`

**Comment by dqshll** [comment]
Thanks for your reply. I’ve already setup ssl based on your image with some extension, below is my Dockerfile:


FROM yiisoftware/yii2-php:7.1-apache
EXPOSE 443
RUN a2enmod rewrite
RUN a2enmod ssl
RUN service apache2 restart
CMD apache2-foreground 


It works fine. Thanks again :)
On 06/30/2019 19:54，Tobias Munk<notifications@github.com> wrote：

The ssl conf is from the PHP base-image, I think.
We did not prepare the image to run with SSL enabled, although this is possible with a self-signed cert for testing; I'd recommend to do the SSL-Termination with a proxy like jwilder/nginx or traefik
