### ISSUE TITLE
phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by yht** [yiisoft/yii2-app-basic#210]
### What steps will reproduce the problem?

`composer create-project --prefer-dist yiisoft/yii2-app-basic yii2-app-basic`

### What's expected?

There're no errors or warnings.

### What do you get instead?

```
codeception/base suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/base suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
codeception/base suggests installing stecman/symfony-console-completion (For BASH autocompletion)
**Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.**
Writing lock file
Generating autoload files
> yii\composer\Installer::postCreateProject
chmod('runtime', 0777)...done.
chmod('web/assets', 0777)...done.
chmod('yii', 0755)...done.
> yii\composer\Installer::postInstall
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | current
| PHP version      | 7.0.33-0+deb9u3
| Operating system | Debian GNU/Linux 9.9 (stretch)

**Comment by samdark** [comment]
We can not fix it without bumping minimum required PHP versions as far as I know. If you know a way, suggestions are welcome.

**Comment by rob006** [comment]
> We can not fix it without bumping minimum required PHP versions as far as I know.

Bumping required PHP version sounds like right thing to do. Targeting PHP 5.4 for project starter in 2019 sounds crazy. Project template should always use modern tools and target recent standards - it is used for new projects, and most of the people don't want to start a new project from "outdated" level. Starting with old phpunit or codeception will just give more paint on upgrade in future.

**Comment by My6UoT9** [comment]
I have quickly tried if its possible to "disable" phpunit-mock-objects, as far as I can tell it works, my php unit tests did run successfully.
But I don't even know if mock objects is in use in my code. Not familiar enough with it.
Maybe someone else can check that?

Add this to composer:
```
  "replace": {
    "phpunit/phpunit-mock-objects": "*"
  },
```

**Comment by hondacivic1** [comment]
Pinches inutiles q n tienen wevos

**Comment by hondacivic1** [comment]
Pinches culos x q n dan la cara culos x q saben q les va cargar la verga

**Comment by DiscipleOfShinku** [comment]
> minimum required PHP versions

Is that why [an old version of Codeception](https://github.com/Codeception/Codeception/issues/5794#issuecomment-568531612) is used?

**Comment by samdark** [comment]
No. We're on 4.x https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L26. I've tried with latest version and is seems the problem isn't there anymore.

**Comment by DiscipleOfShinku** [comment]
Oh! There was an upgrade recently.

**Comment by yht** [comment]
> 
> 
> No. We're on 4.x https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json#L26. I've tried with latest version and is seems the problem isn't there anymore.

Wow, thanks!
