### ISSUE TITLE
Composer Install

### ISSUE THREAD

**Issue by Eloy-Gonzalez** [yiisoft/yii2-app-basic#215]
### What steps will reproduce the problem?
Try using this command from terminal 

`composer create-project --prefer-dist yiisoft/yii2-app-basic basic`

but composer download framework with version 2.0.26, my computer recently has been formated 
Why download yii framework Version 2.0.26?
![composer](https://user-images.githubusercontent.com/20262284/68244906-35b61180-ffec-11e9-9630-03badd152dd3.png)

### What's expected?

Download Yii framework version 2.0.29

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | None
| PHP version      | 7.3.1
| Operating system | Linux Mint 19.2

**Comment by samdark** [comment]
Likely because I've skipped releasing apps last few times. Will fix that in the next release.

**Comment by samdark** [comment]
Meanwhile, `composer update` should do the job.

**Comment by rob006** [comment]
Nothing was changed since `2.0.26` release of template. It does not contain `composer.lock`, so `create-project` should already install latest version of Yii.

**Comment by samdark** [comment]
Ah, right. 2.0.26 is the version of the template. Yii version installed is latest. Thanks, @rob006.
