### ISSUE TITLE
Provide IDE autocomplete hints

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii2-app-basic#216]
### What steps will reproduce the problem?

For example:

Trying to autocomplete `Yii::$app->user->identity->` in an IDE (PHPStorm/Netbeans/etc...) does not show methods and properties of the configured `identityClass`. This is because the IDE has no knowledge about the Yii specific configuration.

We can add hints for these in a file e.g. `config/__autocomplete.php`:

```php
<?php

/**
 * This class only exists here for IDE (PHPStorm/Netbeans/...) autocompletion.
 * This file is never included anywhere.
 */
class Yii {
    /**
     * @var \yii\web\Application|\yii\console\Application|__HostingApplication
     */
    public static $app;
}

/**
 * @property yii\rbac\DbManager $authManager
 * @property yii\queue\redis\Queue $queue
 * @property __WebUser $user
 */
class __HostingApplication {
}

/**
 * @property app\models\User $identity
 */
class __WebUser {
}
```

My suggestion is to add this file to the application templates by default. What do you think?

**Comment by samdark** [comment]
Sounds fine.
