### ISSUE TITLE
Yii2 rest with oracle

### ISSUE THREAD

**Issue by faradoxuz** [yiisoft/yii2-app-basic#23]
Hi, when I'm trying select some data from db, it throws me an error, 'Undefined index: CONSTRAINT_TYPE'. What's the problem? help me please

**Comment by samdark** [comment]
It is definitely not about basic project template so please report at https://github.com/yiisoft/yii2 providing clear details on how to reproduce it. DB schema, steps, error stacktrace etc. Thanks.
