### ISSUE TITLE
Older version in composer.json after installing latest version

### ISSUE THREAD

**Issue by Yousha** [yiisoft/yii2-app-basic#235]
### What steps will reproduce the problem?
1- Open system's terminal/console.
2- Enter the following command: 
`composer create-project --prefer-dist yiisoft/yii2-app-basic basic`
### What's expected?
Install latest version of "yiisoft/yii2-app-basic", both in **vendor** folder and **composer.json** file.
### What do you get instead?
Yii2 installs latest version in Vendor folder, but **old one in composer.json** file.

**composer.json file:**
"yiisoft/yii2": "~2.0.14",

**Vendor folder:**
yiisoft/yii2 2.0.37

### Additional info

`Creating a "yiisoft/yii2-app-basic" project at "./basic"
Installing yiisoft/yii2-app-basic (2.0.37)
  - Installing yiisoft/yii2-app-basic (2.0.37): Downloading (100%)
Created project in C:\WWW\root\basic
Loading composer repositories with package information
Updating dependencies
Package operations: 21 installs, 0 updates, 0 removals
  - Installing yiisoft/yii2-composer (2.0.10): Downloading (100%)
  - Installing symfony/polyfill-mbstring (v1.18.1): Downloading (100%)
  - Installing symfony/polyfill-intl-normalizer (v1.18.1): Downloading (100%)
  - Installing bower-asset/jquery (3.5.1): Downloading (100%)
  - Installing bower-asset/bootstrap (v3.4.1): Downloading (100%)
  - Installing bower-asset/yii2-pjax (2.0.7.1): Downloading (100%)
  - Installing bower-asset/punycode (v1.3.2): Downloading (100%)
  - Installing bower-asset/inputmask (3.3.11): Downloading (100%)
  - Installing cebe/markdown (1.2.1): Downloading (100%)
  - Installing ezyang/htmlpurifier (v4.13.0): Downloading (100%)
  - Installing yiisoft/yii2 (2.0.37): Downloading (100%)
  - Installing yiisoft/yii2-bootstrap (2.0.10): Downloading (100%)
  - Installing symfony/polyfill-php72 (v1.18.1): Downloading (100%)
  - Installing paragonie/random_compat (v9.99.99): Downloading (100%)
  - Installing symfony/polyfill-php70 (v1.18.1): Downloading (100%)
  - Installing symfony/polyfill-intl-idn (v1.18.1): Downloading (100%)
  - Installing symfony/polyfill-iconv (v1.18.1): Downloading (100%)
  - Installing doctrine/lexer (1.2.1): Downloading (100%)
  - Installing egulias/email-validator (2.1.20): Downloading (100%)
  - Installing swiftmailer/swiftmailer (v6.2.3): Downloading (100%)
  - Installing yiisoft/yii2-swiftmailer (2.1.2): Downloading (100%)`

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.37
| PHP version      | 7.4
| Operating system | Windows 10 64bit

**Comment by samdark** [comment]
`~2.0.14` means 2.0.14 and up. That's correct.
