### ISSUE TITLE
token hiden error when run any composer or any other program 

### ISSUE THREAD

**Issue by wasimkhanpathan** [yiisoft/yii2-app-basic#24]
![error](https://cloud.githubusercontent.com/assets/14059547/9605527/11589ae2-5073-11e5-8240-46dd79fba1db.png)
 this error is displing when i install any liabarary in my yii2 aplication please help me as early as posible

**Comment by githubjeka** [comment]
Your should generate new token in https://github.com/settings/tokens and copy&paste in cmd.
Good luck and use forum or chat , because it's bugtracker.

**Comment by wasimkhanpathan** [comment]
what can i written in Token description

**Comment by wasimkhanpathan** [comment]
I jsut take a token number but its not run in cmd what can i do for that..
