### ISSUE TITLE
Install of yiisoft/yii2-composer failed on Composer v2.x

### ISSUE THREAD

**Issue by alexustsb** [yiisoft/yii2-app-basic#241]
### What steps will reproduce the problem?

1. Install Composer v2:
`curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --2`
2. Try to install Yii2 Basic app 
`composer create-project --prefer-dist yiisoft/yii2-app-basic /app`

### What's expected?

Installed Basic app

### What do you get instead?

Error:

- Installing yiisoft/yii2-composer (2.0.10): Extracting archive
Plugin initialization failed (include(/app/vendor/yiisoft/yii2-composer/Plugin.php): failed to open stream: No such file or directory), uninstalling plugin
- Removing yiisoft/yii2-composer (2.0.10)
    Install of yiisoft/yii2-composer failed

  [ErrorException]
  include(/app/vendor/yiisoft/yii2-composer/Plugin.php): failed to open stream: No such file or directory

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | Installing yiisoft/yii2-app-basic (2.0.40)
| PHP version      | PHP 7.4.3
| Operating system | Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-51-generic x86_64)
| Temporary solution | Downgrade to Composer version 1.10.20

**Comment by samdark** [comment]
Tried locally with Composer 2.0.7 and Composer 2.0.9. Works well with exactly your commands. What Composer 2 version do you have?

**Comment by alexustsb** [comment]
>What Composer 2 version do you have?

That was composer 2.0.10 (last on feb 1)

> Tried locally

Maybe you have already installed composer v1/v2 plugins that continue working locally after you change composer version.
My install was on new VirtualBox os system without any composer or composer plugns prewiously installed.
I used Yii2 standart Vagrantfile to run virtual machin first and than run yii2 install via composer v2.
Only change was in line https://github.com/yiisoft/yii2-app-basic/blob/master/vagrant/provision/once-as-root.sh#L79:
`curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --2`

**Comment by middaparka** [comment]
I can confirm that this happens on a clean laravel/homestead box, using Composer 2.0.11…

```
 - Installing yiisoft/yii2-composer (2.0.10): Extracting archive
Plugin initialization failed (include(/…/vendor/yiisoft/yii2-composer/Plugin.php): Failed to open stream: No such file or directory), uninstalling plugin
  - Removing yiisoft/yii2-composer (2.0.10)
    Install of yiisoft/yii2-composer failed

  [ErrorException]                                                                                                                                          
  include(/…/vendor/yiisoft/yii2-composer/Plugin.php): Failed to open stream: No such file or directory  
```

**Comment by samdark** [comment]
@darkdef verified that it doesn't happen on a clean installation of Ubuntu 20.04.2 with Composer 2.0.11 and PHP 7.4.3 made in VirtualBox. Tried both root (with /app directory) and non-root variants. Everything was done manually so I suspect that the error is in https://github.com/yiisoft/yii2-app-basic/tree/master/vagrant.

**Comment by middaparka** [comment]
@samdark I managed to track down the issue I was having (it was related to folder mappings in Homestead - it's necessary to use `type: "nfs"`) and the problem went away.

Exceptionally sorry that I forgot to update this issue. 😬

**Comment by samdark** [comment]
Thanks for update. That will save us some time :)
