### ISSUE TITLE
Wrong attribute inside User.php

### ISSUE THREAD

**Issue by rfiedler** [yiisoft/yii2-app-basic#242]
### What steps will reproduce the problem?
1- site/login
2- Login ok
3- Error - Undefined property: app\models\User::$authKey

### What's expected?
Login correctly

### What do you get instead?
Error - Undefined property: app\models\User::$authKey

### Additional info
Migration create user table with "auth_key" attribute but User Model call incorrect attribute inside function getAuthKey

public function getAuthKey()
{
        return $this->authKey; <- Wrong attribute
        return $this->auth_key; <- correct attribute
}

https://github.com/yiisoft/yii2-app-basic/blob/b1af6fa7f939281878551f5bed527144dfdc974b/models/User.php#L83

| Q                | A
| ---------------- | ---
| Yii vesion       |  2.0.40
| PHP version       | 7.4
| Operating system | Ubuntu 20.04

**Comment by rfiedler** [comment]
Fix this line too:

https://github.com/yiisoft/yii2-app-basic/blob/b1af6fa7f939281878551f5bed527144dfdc974b/models/User.php#L91

**Comment by bizley** [comment]
User model in basic app template is not an Active Record model and it's not related to a database. `authKey` property there is correct. If you are looking for db-based user model you can look at the [User model of advanced app template](https://github.com/yiisoft/yii2-app-advanced/blob/master/common/models/User.php).
