### ISSUE TITLE
Alert widget marks all flash data for deletion

### ISSUE THREAD

**Issue by tobias-dietz** [yiisoft/yii2-app-basic#250]
### What steps will reproduce the problem?

1. Init a new Yii2 project using "yii2-app-basic" template
2. In any route / action that renders a view (or layout) containing the Alert widget, call `Yii::$app->session->setFlash('somekey', 'somevalue')` **before** `$this->render('view');`
3. Open the route from step 2 which renders a view / layout containing the Alert widget
4. Go to another route / action and call `var_dump(Yii::$app->session->getFlash('somekey'));`

### What's expected?

Browser should print `string(9) "somevalue"`

(to be precise, my flash data should be still available because I didn't access it / Alert widget should not touch my flash data)

### What do you get instead?

Browser prints `NULL`

(= my flash data was deleted)

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.43
| PHP version      | 7.4.3, 8.0
| Operating system | Ubuntu 20.04, Alpine Linux 3.14

For step 1, I created a new project by calling `composer create-project --prefer-dist yiisoft/yii2-app-basic basic`

For step 2, I extended the SiteController:

```
public function actionFlashTest() {
    Yii::$app->session->setFlash('somekey', 'somevalue');

    return $this->render('about');
}

public function actionFlashTest2() {
    var_dump(Yii::$app->session->getFlash('somekey'));
    die();
}
```

Then I called `./yii serve`.

For step 3, I went to `http://localhost:8080/index.php?r=site%2Fflash-test`

For step 4, I went to `http://localhost:8080/index.php?r=site%2Fflash-test2`

I've digged into the code, reason for this behavior seems to be that the Alert widget calls on line 54:

https://github.com/yiisoft/yii2-app-basic/blob/4551a05d8892cf370ff7d2fff96e81cbb86dd081/widgets/Alert.php#L54

`Yii::$app->session->getAllFlashes();`

But this call marks **all** flash data for deletion on the next request, also flash data other than error, success, info ...

https://github.com/yiisoft/yii2/blob/c21322f0c60ecd66da07b461469f62979141a828/framework/web/Session.php#L847

My fix (barely tested since my project is in an early stage):

// widgets/Alert.php

```
public function run()
{
    $session = Yii::$app->session;
    $appendClass = isset($this->options['class']) ? ' ' . $this->options['class'] : '';

    foreach ($this->alertTypes as $type) {

        $flash = Yii::$app->session->getFlash($type);
        
        foreach ((array) $flash as $i => $message) {
            echo \yii\bootstrap4\Alert::widget([
                'body' => $message,
                'closeButton' => $this->closeButton,
                'options' => array_merge($this->options, [
                    'id' => $this->getId() . '-' . $type . '-' . $i,
                    'class' => $this->alertTypes[$type] . $appendClass,
                ]),
            ]);
        }

        $session->removeFlash($type);
    }
}
```

If someone confirms that this is a bug, I would try to send a pull request (would be my first one ever :-) )

**Comment by bizley** [comment]
You are right, Alert widget should not access all the flashes, only the one configured for it. Please send PR.

**Comment by bizley** [comment]
The same happens for advanced template https://github.com/yiisoft/yii2-app-advanced/blob/master/common/widgets/Alert.php
