### ISSUE TITLE
PHP 8.0 is required by codeception/module-filesystem when trying to install the latest basic template after 2.0.46 release

### ISSUE THREAD

**Issue by lourdas** [yiisoft/yii2-app-basic#274]
### What steps will reproduce the problem?
Try to install the basic app template, using composer with PHP 7.4.30.

### What's expected?
I'd expect the basic app template installed.

### What do you get instead?
I get an error:
```
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
Creating a "yiisoft/yii2-app-basic" project at "./basic"
Info from https://repo.packagist.org: #StandWithUkraine
Installing yiisoft/yii2-app-basic (2.0.46)
  - Downloading yiisoft/yii2-app-basic (2.0.46)
  - Installing yiisoft/yii2-app-basic (2.0.46): Extracting archive
Created project in /home/lourdas/public_html/basic
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codeception/module-filesystem ^3.0 || ^1.1 -> satisfiable by codeception/module-filesystem[3.0.0].
    - codeception/module-filesystem 3.0.0 requires php ^8.0 -> your php version (7.4.30) does not satisfy that requirement.
```
It seems composer tries to pull codeception/module-filesystem 3.0.0, which required PHP 8.0+ and it fails. I read on the news post about 2.0.46 that the minimum PHP version is now raised to PHP 7.4, but this is wrong.

Could you please look into this?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.46
| PHP version      | 7.4.30
| Operating system | Linux (amd64)

**Comment by samdark** [comment]
Interesting... https://github.com/yiisoft/yii2-app-basic/runs/7908558328?check_suite_focus=true Will check it.

**Comment by xbvan** [comment]
I met this too

**Comment by lourdas** [comment]
What I also noticed is that upgrading an existing project (eg. 2.0.43) to 2.0.46 works fine. It's the new project that fails.

**Comment by winternet-studio** [comment]
Just to make it clear, it's too early to move to PHP 8 as a requirement. For us long standing users making our code base PHP 8 compatible is nowhere near straight forward. Hopefully this issue can be resolved soon.

**Comment by winternet-studio** [comment]
Also, I see that PHP requirement is bumped from 5.6 to 7.4 in composer.json of 2.0.46 - but it's not mentioned anywhere in the changelog...

**Comment by erdiertas** [comment]
I'm getting this error too.

**Comment by samdark** [comment]
Ah. Should have been all of these.

**Comment by samdark** [comment]
Do you have time for a pull request?

**Comment by genisaretskiy** [comment]
same problem with new basic app

**Comment by bukarinevgeni** [comment]
I had the same problem - codeception/module-yii2[1.1.0, ..., 1.1.1] require php >=5.6.0 <8.0 -> your php version (8.2.0) does not satisfy that requirement.
I just change "codeception/module-filesystem": "^2.0 || ^1.1" to "codeception/module-filesystem": "^3.0 || ^1.1"
and all works

**Comment by martimluisdev** [comment]
Thanks @bukarinevgeni it also worked for me.
Regards,
<Martim>
