### ISSUE TITLE
options with alias dose not resolved in function registerLinkTag

### ISSUE THREAD

**Issue by xbvan** [yiisoft/yii2-app-basic#275]
### What steps will reproduce the problem?
when I run `yii serve`，I found that request of favicon.ico cause a http 404 error
see `views/layouts/main.php` at line 20，`@web`  dosen't resolved
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       |2.0.46
| PHP version      |7.4.9
| Operating system |Windows 10

**Comment by samdark** [comment]
Fixed.
