### ISSUE TITLE
Can't update 2amigos/qrcode-library

### ISSUE THREAD

**Issue by monta990** [yiisoft/yii2-app-basic#278]
### What steps will reproduce the problem?
Try to update 2amigos/qrcode-library  

composer why 2amigos/qrcode-library
yiisoft/yii2-app-basic - requires 2amigos/qrcode-library (1.1.2)

### What's expected?
Update to the newer version

### What do you get instead?
Fail to updated

### Additional info

The actual version yii2-app-basic depends old version 2amigos/qrcode-library

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.46
| PHP version      | 8.1.10
| Operating system | CentOS 7.9

**Comment by bizley** [comment]
yiisoft/yii2-app-basic does not depend on 2amigos/qrcode-library what you can see [here](https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json).
