### ISSUE TITLE
yii2.0.46 using oci8-could not find driver

### ISSUE THREAD

**Issue by maoyuqiang2022** [yiisoft/yii2-app-basic#280]
### What steps will reproduce the problem?
After installed yii2.0.46，apps runs as normal；
I compiled OCI8 used pecl oci8.3.2.1+oracle client 12.1.0 ，then got oci8.so extension, revise php.ini and test connection to oracle11g.
**tested with PHP,work fine.**
using oci_connect() can connect to oracle and i got data using oci_execute();
but yii2 still warning ''could not find driver''
### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.46
| PHP version      | php8.1.17
| Operating system |rocky8.6

**Comment by maoyuqiang2022** [comment]
[](url)
![2](https://user-images.githubusercontent.com/112047589/197332103-3b253e5d-1469-4ec4-a1b8-a7b518d3b677.png)
![1](https://user-images.githubusercontent.com/112047589/197332108-529c14bd-c109-4ce4-8834-8df4722785b4.png)
![1](https://user-images.githubusercontent.com/112047589/197332109-abd97f27-d14e-4157-91ca-3f0e6391b6c7.png)
![2](https://user-images.githubusercontent.com/112047589/197332111-89974977-1ac1-4192-a324-2e01c06ca6d4.png)

**Comment by bizley** [comment]
How did you test it? Remember that your CLI config may be different than CGI.

**Comment by pyostrike** [comment]
You need this installed and working: https://www.php.net/manual/en/ref.pdo-oci.php

**Comment by maoyuqiang2022** [comment]
Thanks all. yii2 need PDO_OCI,OCI8 extensions, copy from source code,compiled.Then worked。
