### ISSUE TITLE
Wrong version while installation via composer

### ISSUE THREAD

**Issue by em92** [yiisoft/yii2-app-basic#281]
### What steps will reproduce the problem?

```
composer create-project yiisoft/yii2-app-basic basic
```

### What's expected?

Output like `Installing yiisoft/yii2-app-basic (2.0.47)`. 2.0.47 is taken from https://www.yiiframework.com/download

### What do you get instead?

Output like `Installing yiisoft/yii2-app-basic (2.0.45)`.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0
| PHP version      | 7.3
| Operating system | Debian GNU/Linux

**Comment by schmunk42** [comment]
Why is `2.0.47` wrong? It matches the constraint in `composer.json` and there's no `composer.lock` file.

**Comment by schmunk42** [comment]
Sorry my bad.

Min PHP version was raised to 7.4

https://github.com/yiisoft/yii2-app-basic/compare/2.0.45...2.0.47#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R17

**Comment by samdark** [comment]
Closing because the reason is PHP version.
