### ISSUE TITLE
Requirement codeception/module-filesystem ^2.0 || ^1.1 conflicts with codeception/codeception 5.0

### ISSUE THREAD

**Issue by EmileBons** [yiisoft/yii2-app-basic#282]
### What steps will reproduce the problem?
`composer install`

### What's expected?
`21 package suggestions were added by new dependencies, use composer suggest to see details.`
`Generating autoload files`
`56 packages you are using are looking for funding.`
`Use the composer fund command to find out more!`

### What do you get instead?

`  Problem 1`
`    - Root composer.json requires codeception/module-filesystem ^2.0 || ^1.1 -> satisfiable by codeception/module-filesystem[2.0.0, 2.0.1, 2.0.2].`
`    - Conclusion: don't install codeception/codeception 5.0.5 (conflict analysis result)`
`    - Conclusion: don't install codeception/codeception 5.0.6 (conflict analysis result)`
`    - Conclusion: don't install codeception/codeception 5.0.7 (conflict analysis result)`
`    - codeception/module-yii2[1.1.0, ..., 1.1.1] require php >=5.6.0 <8.0 -> your php version (8.2.0) does not satisfy that requirement.`
`    - codeception/module-yii2[1.1.2, ..., 1.1.3] require php >=5.6.0 <8.1 -> your php version (8.2.0) does not satisfy that requirement.`
`    - codeception/module-yii2 1.1.4 requires php >=5.6.0 <=8.1 -> your php version (8.2.0) does not satisfy that requirement.`
`    - codeception/module-yii2 1.1.5 requires php >=5.6.0 <=8.1 | ~8.1.0 -> your php version (8.2.0) does not satisfy that requirement.`
`    - codeception/module-yii2 1.1.6 requires codeception/codeception ^5.0.0 -> satisfiable by codeception/codeception[5.0.0, ..., 5.0.7].`
`    - codeception/module-yii2 1.1.7 requires codeception/codeception ^5.0.0-RC6 -> satisfiable by codeception/codeception[5.0.0, ..., 5.0.7].`
`    - Conclusion: don't install codeception/codeception 5.0.0 (conflict analysis result)`
`    - Root composer.json requires codeception/module-yii2 ^1.1 -> satisfiable by codeception/module-yii2[1.1.0, ..., 1.1.7].`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.45
| PHP version      | 8.2
| Operating system | macOS Ventura 13.0.1

**Comment by SmartGuyCodes** [comment]
I am currently experiencing upon composer installing yii2 app in my Macbook pro Workspace. See attachment for more info
<img width="692" alt="Screenshot 2023-03-08 at 11 19 03" src="https://user-images.githubusercontent.com/74773182/223659613-2ca6bc55-53d4-4b82-8e69-2e53ef1c5301.png">

**Comment by EmileBons** [comment]
@SmartGuyCodes You're responding to a closed issue. The issue you're reporting is an issue in [the codeception module for Yii2 framework](https://github.com/Codeception/module-yii2), please create a new issue there. An easy one to fix: in the composer.json, the php version needs to be updated. Until fixed, downgrade your php version to 8.1.0 and you should be fine.

**Comment by olissongs** [comment]
Hi,

while using php 8.2, this command produces an the same error, using tag 2.0.47 with
composer create-project --prefer-dist yiisoft/yii2-app-basic basic

is there a new release tag planned?

tip for meanwhile:
using composer in branch master
