### ISSUE TITLE
It´s possible update phpunit/phpunit to 10?

### ISSUE THREAD

**Issue by monta990** [yiisoft/yii2-app-basic#284]
https://github.com/yiisoft/yii2-app-basic/blob/980c25ed47545a6c0d12951a731c59cb95f97f9c/composer.json#L26

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.48
| PHP version      | 8.1.14
| Operating system | Centos 7

**Comment by samdark** [comment]
v10 is a breaking release so yes, it is possible but would require rewriting lots of tests or making a polyfill. I'd prefer not to do it for now.
