### ISSUE TITLE
CSS issues with Bootstrap

### ISSUE THREAD

**Issue by lmsmartins** [yiisoft/yii2-app-basic#285]
### What steps will reproduce the problem?
1. Install Yii 2 basic app template.
2. Open the login page, and you'll see the login form is a little off.
3. Create a CRUD for any table, and when opening the create or update page, there is no margin between each "form-group".

### What's expected?
Login form to be properly formatted.
Proper margin-bottom between each "form-group" in a create and update page of a CRUD.

### What do you get instead?
Login form is a little off.
There is no margin-bottom between each "form-group". The form groups are very close to each other.

![login_form](https://user-images.githubusercontent.com/8367143/221366403-9cc98c3f-f7bc-451e-be59-c99264118ea3.png)
![create_update_page_crud](https://user-images.githubusercontent.com/8367143/221366405-6cbf2242-34b0-4a73-97c8-2698e0861b9f.png)

### Additional info
| Q                | A
| ---------------- | ---
| Yii version       |  2.0.47
| PHP version      | 8.1.6
| Operating system | MacOS Ventura 13.0.1

**Comment by bizley** [comment]
Yes, this could be corrected, do you have time for a fix maybe?

**Comment by lmsmartins** [comment]
Yes, I just submitted a PR with the fix: https://github.com/yiisoft/yii2-app-basic/pull/287
