### ISSUE TITLE
How to build projects on top of this repo?

### ISSUE THREAD

**Issue by WeeSee** [yiisoft/yii2-app-basic#311]
How to use this repo to ensure that repo updates are possible`?

I want to use this repo with `docker-compose-yml` as a basis for my little app. 
Since I'm working with PHP 8.2 in my other projects I also want to use Yii2 in this 
project (a big [PR ](https://github.com/yiisoft/yii2-app-basic/pull/305#issue-1797646038) is already waiting for PHP8.x).

How to integrate my code with this repo that future versions of this repo can 
be updated in my project (e.g. keeping my code separate from this repo)?

I'm missing any ideas in Docs or in the Readme.
Please help me out.

**Comment by terabytesoftw** [comment]
You will not have problems, when creating the basic template, since the code you are creating will not change, so you will not have problems of any kind.

**Comment by WeeSee** [comment]
> You will not have problems, when creating the basic template, since the code you are creating will not change, so you will not have problems of any kind.

Maybe I don't understand how this can be done.

When I add my own views, e.g. I'll create files in the `./views` directory and
create my own repo of the project: How to reintegrate the changes of [this  
repo](https://github.com/yiisoft/yii2-app-basic) at a later time in my project?

**Comment by samdark** [comment]
There's no need to do so. Template is template. You start with it and never touch it again.
