### ISSUE TITLE
Unable to run basic Yii2 app

### ISSUE THREAD

**Issue by softal** [yiisoft/yii2-app-basic#36]
I'm following the official Yii install guide
<pre>composer global require "fxp/composer-asset-plugin:~1.1.0"
composer create-project --prefer-dist yiisoft/yii2-app-basic basic
</pre>

After the installation I have try to access the installed application and and there was an error:
<pre>
Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: D:\xampp\htdocs\basic\vendor\bower/jquery/dist
</pre>

When I changed the @bower alias with
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower');
to 
Yii::setAlias('@bower', $this->_vendorPath . DIRECTORY_SEPARATOR . 'bower/bower-asset ');
everything was OK.

**Comment by samdark** [comment]
Do `composer global require "fxp/composer-asset-plugin:~1.1.1"` then re-install.

**Comment by Naktibalda** [comment]
Codeception tests fail for the same reason:

 `The file or directory to be published does not exist: /home/travis/build/Codeception/Codeception/frameworks-yii-basic/vendor/bower/jquery/dist`

in /home/travis/build/Codeception/Codeception/frameworks-yii-basic/vendor/yiisoft/yii2/web/AssetManager.php:452

**Comment by Naktibalda** [comment]
- Installing fxp/composer-asset-plugin (v1.1.1)

    Downloading: 100%

PHP Fatal error:  Call to undefined method Composer\Package\Loader\ArrayLoader::parseLinks() in /home/travis/.composer/vendor/fxp/composer-asset-plugin/Repository/VcsPackageFilter.php on line 279

**Comment by Naktibalda** [comment]
I required the latest version of composer - 1.0.0-alpha11

**Comment by SilverFire** [comment]
@Naktibalda this problem relates to composer-asset-plugin. See https://github.com/francoispluchino/composer-asset-plugin/pull/133#issuecomment-145128571 for solution
