### ISSUE TITLE
retrieve user identity in token based auth.

### ISSUE THREAD

**Issue by su-xiaolin** [yiisoft/yii2-app-basic#40]
in api app.
I config user component with  `enableSession=false`, and use HttpBearerAuth solution。How to retrieve user identity, Yii::$app->user->identity return false, any idea for this solution to retrieve user identity?

**Comment by samdark** [comment]
Are you passing access token around with each request after obtaining it? Why disabling session?

**Comment by samdark** [comment]
Also... it's better to use forums for questions.

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/forum/42-general-discussions-for-yii-20/
