### ISSUE TITLE
composer create-project sucess,BUT can not run web app

### ISSUE THREAD

**Issue by tomjamescn** [yiisoft/yii2-app-basic#41]
## env:
Composer version 1.0-dev (c9501a4cc164b176de48e44b239e619cfd5f14e5) 2015-12-16 18:51:41
fxp/composer-asset-plugin (v1.0.3)

## run:
composer create-project --prefer-dist yiisoft/yii2-app-basic basic

## visit in browser, show this exception:
```
Invalid Parameter – yii\base\InvalidParamException

The file or directory to be published does not exist: /Users/tomjamescn/my_develop_space/php_workspace/test/basic/vendor/bower/jquery/dist
```

in the dir ./vender/bower has this subdirs:
bower-asset

jquery dir is under bower-asset dir.

One month ago, there is no problem~

**Comment by tomjamescn** [comment]
if i redefin @bower in Application can fix this exception.

But, why this happen? May be my env is something wrong?

**Comment by SilverFire** [comment]
It's a common question and it was discussed many times. Your fxp-plugin is outdated.

`php composer.phar global require "fxp/composer-asset-plugin:~1.1.0"`
