### ISSUE TITLE
migration how to AUTO_INCREMENT  a filed

### ISSUE THREAD

**Issue by noname007** [yiisoft/yii2-app-basic#42]
like this sql ` id int(11) NOT NULL AUTO_INCREMENT`,the AUTO_INCREMENT how to be added

**Comment by SilverFire** [comment]
Define this field as `->primaryKey()`, then `AUTO_INCREMENT` will be added automatically.

**Comment by noname007** [comment]
but i not find the  method in 2.0.6

**Comment by SilverFire** [comment]
It actually exists since 2.0.6. Check out http://www.yiiframework.com/doc-2.0/yii-db-schemabuildertrait.html#primaryKey()-detail

And the example: https://github.com/yiisoft/yii2-app-advanced/blob/master/console/migrations/m130524_201442_init.php

**Comment by noname007** [comment]
but i was rellay don't find the function in the yii2 code
and the project created by composer  

![Uploading 1.png…]()

**Comment by SilverFire** [comment]
I've pointed you to the [SchemaBuilderTrait](https://github.com/yiisoft/yii2/blob/2.0.6/framework/db/SchemaBuilderTrait.php#L49), and you are showing `ColumnSchemaBuilder`

**Comment by noname007** [comment]
Sorrry stereotype,not notice the class name !!
