### ISSUE TITLE
Problem with @tests alias in Codeception config file after console command

### ISSUE THREAD

**Issue by StickeydM** [yiisoft/yii2-app-basic#53]
`@tests` alias in `codeception/config/config.php` seems not to be working correctly if it loads after main console config file. And this is excatly the way how it loads when you try to start console commands from `codeception/bin` folder.

```
$config = yii\helpers\ArrayHelper::merge(
    require(YII_APP_BASE_PATH . '/config/console.php'),
    require(__DIR__ . '/../config/config.php')
);
```

It's happening because of `@app/config/console.php` config file, because of this code 
`Yii::setAlias('@tests', dirname(__DIR__) . '/tests/codeception');`

After console command, in codeception/config/config.php file `@tests` alias value is `'ProjectFolder/tests/codeception'`, but after that there are lines trying to add additional `'codeception'` folder 

```
    'controllerMap' => [
        'fixture' => [
            'class' => 'yii\faker\FixtureController',
            'fixtureDataPath' => '@tests/codeception/fixtures',
            'templatePath' => '@tests/codeception/templates',
            'namespace' => 'tests\codeception\fixtures',
        ],
    ],
```

So if you're trying generate a fixture for example, the path is not working correctly.

**Comment by SilverFire** [comment]
Not valid after tests refactoring.
