### ISSUE TITLE
rest api Not Found

### ISSUE THREAD

**Issue by shyandsy** [yiisoft/yii2-app-basic#54]
### What steps will reproduce the problem?
I try to create some rest APIs for my app follow the tutorial 
http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html

step 1:create a new project based on the basic template by composer
step 2:Creating a Controller
step 3:Configuring URL Rules
step 4:Enabling JSON Input
step 5:Trying it Out
 
### What's expected?
not found
![image](https://cloud.githubusercontent.com/assets/5271457/14592972/940af896-04ea-11e6-9b22-afd7d5451001.png)

### Additional info
could you provide an example project (or a rest api template)? 

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.7
| PHP version      |7.0.3
| Operating system |centos 7 x64

**Comment by cebe** [comment]
How did you configure URL rules? Note that URLs are pluralised.

**Comment by shyandsy** [comment]
exactly sane as the tutorial

**Comment by cebe** [comment]
http://www.yiiframework.com/doc-2.0/guide-rest-quick-start.html#trying-it-out
>     Info: Yii will automatically pluralize controller names for use in endpoints. You can configure this using the yii\rest\UrlRule::$pluralize-property.
