### ISSUE TITLE
Codeception specify causes Maximum function nesting level error

### ISSUE THREAD

**Issue by cherifGsoul** [yiisoft/yii2-app-basic#56]
### What steps will reproduce the problem?
Runing unit tests examples cause errors ```Maximum function nesting level``` the first test works fine but others dont work
### Additional info
It seems that ```Codeception\Specify\Config``` have ```setDeepClone``` property that can be set to ```false``` and all tests pass after puting that
### more details 
https://github.com/Codeception/Specify/blob/master/docs/GlobalConfig.md

**Comment by cherifGsoul** [comment]
It has local configuration also
https://github.com/Codeception/Specify/blob/master/docs/LocalConfig.md

**Comment by SilverFire** [comment]
I think you have XDebug with nested level limitations. Add the following line to your php.ini and the problem should disappear.

```ini
xdebug.max_nesting_level = 200
```

**Comment by cherifGsoul** [comment]
Thank you @SilverFire, but I disagree closing the issue even if the solution above works the tests remain slow and are consume a lot of memory, can you imagine more than 800 MO for the simple tests examples in the  basic app template?? I think good test examples should be present. for now I deactivate the deep cloning for my integration tests because the connection to the database is already slow.

**Comment by SilverFire** [comment]
@yiisoft/core-developers any other opinions?

**Comment by cebe** [comment]
is there a good way to fix this issue in yii application template code?

**Comment by cherifGsoul** [comment]
@cebe Im still investigating the deep cloning in the ```codeception\specify``` lib and how it can be limited just to the needed properties in the test

**Comment by cherifGsoul** [comment]
It seems that even the user component properties are cloned so, in ```LoginFormTest``` (the class that causes the issue) I put:
```php
protected function setUp()
 {
        parent::setUp();
        $this->specifyConfig()->cloneOnly('model');
}
```
and all the tests passe faster and less memory consumed:
With: 
```codecept run unit``` 
I got
 ```Time: 655 ms, Memory: 22.25Mb```

With:
```codecept run unit models/LoginFormTest```
I got:
```Time: 508 ms, Memory: 16.00Mb```

Without the solution above the affected test only took:
```Time: 10.73 seconds, Memory: 93.75Mb```

Any toughts @cebe @samdark @SilverFire ??

**Comment by samdark** [comment]
https://github.com/Codeception/Codeception/issues/2516#issuecomment-209917193

**Comment by samdark** [comment]
Could be set up by default, I think.

**Comment by cherifGsoul** [comment]
@samdark yeah, I mentionned that in the main issue description and it is how I use it right now, but the specify documentation says that the properties cloning helps to isolate the test subject (Im still confused about that) so I dont want to remove this feature, so my solution clone only the test subject, maybe we can let the user make the decision to disable it in the whole test suit or not.

**Comment by samdark** [comment]
https://github.com/Codeception/Codeception/issues/2516#issuecomment-219665653

**Comment by cherifGsoul** [comment]
So the decision to make is the disable it by default in the bootstrap?

**Comment by samdark** [comment]
Yes. That and adding notes right where it's disabled.

**Comment by cherifGsoul** [comment]
ok thank you @samdark

**Comment by cherifGsoul** [comment]
The PR was sent
