### ISSUE TITLE
Port in external redirect in Codeception Acceptance Test

### ISSUE THREAD

**Issue by asasmoyo** [yiisoft/yii2-app-basic#59]
### What steps will reproduce the problem?
On a new basic yii2 project, create a controller and action which return redirect response to external domain.
For example:
```php
class FooController extends Controller {
    public function actionRedirect() {
        return $this->redirect('http://google.com');
    }
}
```
Next create an acceptance test opening the action url with ``amOnPage`` method.
For example:
```php
$i = new AcceptanceTester($scenario);
$i->amOnPage('index-test.php?r=foo/redirect');
```
Then run ``php yii serve`` and run the acceptance test ``codecept run acceptance``.

### What's expected?
It should be redirected to ``http://google.com``, not ``http://google.com:8080``. I think the ``8080`` port comes from ``test_entry_url`` on ``codeception.yml`` or ``PhpBrowser.url`` on ``acceptance.suite.yml``. When i change both of them to 80 and run ``php yii serve`` on port 80, it redirects to ``http://google.com``.

### What do you get instead?
```bash
[GuzzleHttp\Exception\ConnectException] cURL error 7: Failed to connect to google.com port 8080: Timed out
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | >=2.0.5
| PHP version      | PHP 7.0.4 from Xampp 3.2.2
| Operating system | Windows 10

**Comment by DavertMik** [comment]
Looks like a pretty familiar but an old version of Codception.
Please update Codeception and try again

**Comment by asasmoyo** [comment]
ah yes, it seems there is bug on the older codeception. i just confirmed that the redirect works on the latest version yii2 basic with codeception 2.2.3. 
thanks @DavertMik
