### ISSUE TITLE
Can't run migration without foreign key error

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-app-basic#63]
### What steps will reproduce the problem?
codeception/bin/yii migrate
Yii Migration Tool (based on Yii v2.0.8)

Creating migration history table "migration"...Done.
Total 7 new migrations to be applied:
	m141201_013120_create_status_table
	m150128_003709_extend_status_table_for_created_by
	m150128_233458_extend_status_table_for_slugs
	m150209_200619_extend_status_table_for_updated_by
	m150209_204852_create_status_log_table
	m150219_235923_create_sample_table
	m160316_201654_extend_status_table_for_image

Apply the above migrations? (yes|no) [no]:yes
*** applying m141201_013120_create_status_table
    > create table {{%status}} ... done (time: 0.006s)
*** applied m141201_013120_create_status_table (time: 0.023s)

*** applying m150128_003709_extend_status_table_for_created_by
    > add column created_by integer NOT NULL to table {{%status}} ... done (time: 0.008s)
    > add foreign key fk_status_created_by: {{%status}} (created_by) references {{%user}} (id) ...Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1005 Can't create table 'yii2_basic_tests.#sql-98f_22' (errno: 150)
The SQL being executed was: ALTER TABLE `status` ADD CONSTRAINT `fk_status_created_by` FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE'

### What's expected?
Completed migration

### What do you get instead?
error above

### Additional info

Adding foreign keys for the test fails.

I did a composer self-update and composer-update before re-testing. The db permissions do work, status table is created okay. 

Also codeception is installed properly.

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
The error comes from MySQL, not from Yii. I guess you have more than a single `fk_status_created_by` and it should be unique.

**Comment by samdark** [comment]
Or it could be type mismatch...

**Comment by samdark** [comment]
Execute "SHOW ENGINE INNODB STATUS" right after error and look for "LATEST FOREIGN KEY ERROR".

**Comment by newscloud** [comment]
Sam, thanks for the quick reply.

Does this have to do with me running the yii tests on yii2_basic_tests db vs. my app's hello db? Hello db has user table, yii2_b_t does not. But, I was following instructions...

=====================================
160630 11:48:18 INNODB MONITOR OUTPUT
=====================================
Per second averages calculated from the last 16 seconds
-----------------
BACKGROUND THREAD
-----------------
srv_master_thread loops: 122 1_second, 122 sleeps, 11 10_second, 13 background, 13 flush
srv_master_thread log flush and writes: 121
----------
SEMAPHORES
----------
OS WAIT ARRAY INFO: reservation count 12, signal count 12
Mutex spin waits 2, rounds 35, OS waits 0
RW-shared spins 12, rounds 360, OS waits 12
RW-excl spins 0, rounds 0, OS waits 0
Spin rounds per wait: 17.50 mutex, 30.00 RW-shared, 0.00 RW-excl
------------------------
LATEST FOREIGN KEY ERROR
------------------------
160629 17:50:00 Error in foreign key constraint of table yii2_basic_tests/#sql-98f_2c:
FOREIGN KEY (`created_by`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE:
Cannot resolve table name close to:
(`id`) ON DELETE CASCADE ON UPDATE CASCADE
------------
TRANSACTIONS
------------
Trx id counter 103777
Purge done for trx's n:o < 103775 undo n:o < 0
History list length 1686
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 0, not started
MySQL thread id 52, OS thread handle 0x7000007ae000, query id 773 localhost root
SHOW ENGINE INNODB STATUS
--------
FILE I/O
--------
I/O thread 0 state: waiting for i/o request (insert buffer thread)
I/O thread 1 state: waiting for i/o request (log thread)
I/O thread 2 state: waiting for i/o request (read thread)
I/O thread 3 state: waiting for i/o request (read thread)
I/O thread 4 state: waiting for i/o request (read thread)
I/O thread 5 state: waiting for i/o request (read thread)
I/O thread 6 state: waiting for i/o request (write thread)
I/O thread 7 state: waiting for i/o request (write thread)
I/O thread 8 state: waiting for i/o request (write thread)
I/O thread 9 state: waiting for i/o request (write thread)
Pending normal aio reads: 0 [0, 0, 0, 0] , aio writes: 0 [0, 0, 0, 0] ,
ibuf aio reads: 0, log i/o's: 0, sync i/o's: 0
Pending flushes (fsync) log: 0; buffer pool: 0
441 OS file reads, 378 OS file writes, 114 OS fsyncs
0.00 reads/s, 0 avg bytes/read, 0.00 writes/s, 0.00 fsyncs/s
-------------------------------------
INSERT BUFFER AND ADAPTIVE HASH INDEX
-------------------------------------
Ibuf: size 1, free list len 0, seg size 2, 0 merges
merged operations:
insert 0, delete mark 0, delete 0
discarded operations:
insert 0, delete mark 0, delete 0
Hash table size 276707, node heap has 1 buffer(s)
0.00 hash searches/s, 0.00 non-hash searches/s
---
LOG
---
Log sequence number 31703945
Log flushed up to   31703945
Last checkpoint at  31703945
0 pending log writes, 0 pending chkp writes
81 log i/o's done, 0.00 log i/o's/second
----------------------
BUFFER POOL AND MEMORY
----------------------
Total memory allocated 137363456; in additional pool allocated 0
Dictionary memory allocated 56277
Buffer pool size   8192
Free buffers       7755
Database pages     436
Old database pages 0
Modified db pages  0
Pending reads 0
Pending writes: LRU 0, flush list 0, single page 0
Pages made young 0, not young 0
0.00 youngs/s, 0.00 non-youngs/s
Pages read 430, created 6, written 361
0.00 reads/s, 0.00 creates/s, 0.00 writes/s
No buffer pool page gets since the last printout
Pages read ahead 0.00/s, evicted without access 0.00/s, Random read ahead 0.00/s
LRU len: 436, unzip_LRU len: 0
I/O sum[0]:cur[0], unzip sum[0]:cur[0]
--------------
ROW OPERATIONS
--------------
0 queries inside InnoDB, 0 queries in queue
1 read views open inside InnoDB
Main thread id 123145309814784, state: waiting for server activity
Number of rows inserted 10, updated 0, deleted 0, read 37
0.00 inserts/s, 0.00 updates/s, 0.00 deletes/s, 0.00 reads/s
----------------------------
END OF INNODB MONITOR OUTPUT
============================

**Comment by samdark** [comment]
Based on the error, it's using correct database.

**Comment by samdark** [comment]
Reading what it says it seems it can't resolve `user` table name. Does `user` table exists at the moment you're trying to reference it?

**Comment by newscloud** [comment]
Sorry Sam, I thought these were internal codeception-oriented Yii migrations because following the documentation, I did 
cd tests
codeception/bin/yii migrate

However, it is instead running my apps own migrations.

a) Is there documentation for exact steps for running codeception tests against Yii Framework and properly configuring yii2_basic_tests?

b) Also from my email, I'm unable to get functional or unit tests working either. It would be helpful to see documentation for creating an example functional test or unit test. Simple acceptance tests work fine.

**Comment by pstddc** [comment]
> add foreign key fk_status_created_by: {{%status}} (created_by) references {{%user}} (id)

O_o

**Comment by samdark** [comment]
a) Yes: https://github.com/yiisoft/yii2-app-basic/blob/master/tests/README.md

b) There were some errors in unit tests caused by phpunit deprecations. I've fixed that.

Other than that it seems to be fine:

Install basic app, then install codeception and plugins (you may have these globally, I did not so installed these locally):

```
composer require codeception/codeception 
composer require codeception/verify
composer require codeception/specify
```

Build codeception actors:

```
cd app_dir/tests
./../vendor/codeception/codeception/codecept build (it could be just codecept build if you have it installed globally) 
cd app_dir
./yii serve (running web server is required for acceptance tests to work)
```

Now open another shell w/o closing web server.

```
cd app_dir/tests
./../vendor/codeception/codeception/codecept run
```

**Comment by newscloud** [comment]
Sam, running ./yii serve fixes running the tests when I run them from the /hello directory - but not when I try to run actual login code and access the default login test library

a) Are you supposed to codecept run from app-basic/tests all the time? why are there app-basic/tests/acceptance, functional and unit directories as well as app-basic/tests/codeception/acceptance, functional and unit ? What's the difference? Should I delete some?

b) The migration error still occurs but it may be due to dektrium usage. See http://pastebin.com/hyHbgK6y . I deleted all the tables in the hello db and ran migration from scratch again. And, then, I deleted all the tables in yii2-app-basic as well. 

c) When I try to add real code to the app-basic/tests/functional LoginCept.php, it breaks.
<?php
use tests\codeception\_pages\LoginPage;
$I = new FunctionalTester($scenario);
$loginPage = LoginPage::openBy($I);
$I->see('Login', 'h1');

$ cd ~/sites/hello
$ codecept run
Codeception PHP Testing Framework v2.1.11
Powered by PHPUnit 5.3.5 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------------------------------------------------------
Ensure that frontpage works (WelcomeCept)                                                             Ok
------------------------------------------------------------------------------------------------------------

Functional Tests (1) ----------------------------------------------------------
Running LoginCept ... 


FATAL ERROR. TESTS NOT FINISHED.
Class 'tests\codeception\_pages\LoginPage' not found 
in /Users/Jeff/Sites/hello/tests/functional/LoginCept.php:5

If I go to $cd ~/sites/hello/tests, then I get the error in the PasteBin that's specific to Dektrium.

 d) Note: on https://github.com/yiisoft/yii2-app-basic/blob/master/tests/README.md, I suggest rewriting the instruction for "cd tests" ahead of codeception/bin/yii migrate. "The command needs to be run in the tests directory. " isn't as clear as it could be.

**Comment by samdark** [comment]
a)

> Are you supposed to codecept run from app-basic/tests all the time?

Yes. You need to run it from where `codeception.yml` is.

> why are there app-basic/tests/acceptance, functional and unit directories as well as app-basic/tests/codeception/acceptance, functional and unit ? What's the difference? Should I delete some?

I don't have app-basic/tests/acceptance, functional and unit directories. I guess you can delete it and not sure why you have it at all...

As for directories:

- unit tests = usual unit style tests
- functional tests = tests from user perspective i.e. clicking a link, loading a page, checking for HTML presence etc. Running w/o actually starting a browser or web driver. No JavaScript.
- acceptance tests = same user perspective tests as functional but works in a real browser and real web server. JavaScript could work, browser issues could be tested.


b) Yes. It's the error in migrations. Seems to be about mismatch of FK source and target column types but I'm not sure it is. You need to get error message itself, it's not that straightforward with MySQL and InnoDB (check google on how) or just use MariaDB.

c) Do you have that `\tests\codeception_pages\LoginPage` class defined?

d) OK.

**Comment by newscloud** [comment]
Thanks Alex. Looks like my next step will be to delete the /tests/acceptance, functional and unit files and try again using the /tests/codeception/acceptance, functional and unit files.

Thanks for your help!
