### ISSUE TITLE
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder()

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-app-basic#64]
### What steps will reproduce the problem?
codecept run
### What's expected?
the test will work

### What do you get instead?
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder()

### Additional info

In tests/unit/contactformtest...
public function testContact()
    {
        $model = $this->getMock('app\models\ContactForm', ['validate']);
        $model->expects($this->once())->method('validate')->will($this->returnValue(true));

replacing with createMock seems to fix it

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
Already fixed.
