### ISSUE TITLE
Unit ContactFormTest.php Doesn't Work

### ISSUE THREAD

**Issue by newscloud** [yiisoft/yii2-app-basic#65]
### What steps will reproduce the problem?
codecept run
### What's expected?
test will pass

### What do you get instead?
The email files generated begin with a datestamp and then .eml extension. testing_message.eml never exists. Test always fails.

    private function getMessageFile()
    {
        return Yii::getAlias(Yii::$app->mailer->fileTransportPath) . '/testing_message.eml';
    }

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
Update from master. It's already fixed. Was because of changes in PHPUnit. Will be tagged with 2.0.9 release.

**Comment by newscloud** [comment]
@samdark just fyi - I looked and don't see the change to the filenames that it's looking for to validate the test
 private function getMessageFile()
    {
        return Yii::getAlias(Yii::$app->mailer->fileTransportPath) . '/testing_message.eml';
    }

I looked on yii2-basic master but not sure if I was looking to the wrong tree.

**Comment by samdark** [comment]
master is the right tree. There's no path change. It was wrong mocking method that was causing issues.
