### ISSUE TITLE
ContactFormTest tearDown can't be executed

### ISSUE THREAD

**Issue by githubjeka** [yiisoft/yii2-app-basic#7]
I got a error

```
yii\base\ErrorException: unlink(C:\Users\Evgeniy\Documents\basic\runtime/mail/testing_message.eml): No such file or directory
```

in [this line](https://github.com/yiisoft/yii2-app-basic/blob/master/tests/codeception/unit/models/ContactFormTest.php#L23)
when [returned `false`](https://github.com/yiisoft/yii2-app-basic/blob/master/models/ContactForm.php#L61)

You need to add `@` or the check `is_file`.

**Comment by samdark** [comment]
Doesn't seem to be valid anymore.
