### ISSUE TITLE
Running of functional tests creates directory @webroot with garbage. 

### ISSUE THREAD

**Issue by dmitry-kulikov** [yiisoft/yii2-app-basic#77]
### What steps will reproduce the problem?

`composer exec codecept run functional`

### What's expected?

Tests pass.

### What do you get instead?

Tests pass, but directory `@webroot/assets` was created, it contains JS, CSS etc., these files are not gitignored.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.9
| PHP version      | PHP 5.5.9-1ubuntu4.17
| Operating system | Linux

Probably reason of this lies here https://github.com/Codeception/Codeception/blob/0e268a10e2e5c7d640a70ddf7dc7d558f2d3b0c1/src/Codeception/Lib/Connector/Yii2.php#L253:L256. I guess need to stub AssetManager in such way to prevent real publishing of assets or use real AssetManager and publish files correctly.

**Comment by samdark** [comment]
I think we need to prevent assets publishing. @DavertMik as I remember, you've attempted doing that, haven't you?

**Comment by DavertMik** [comment]
No it's not related to AssetManager replacement in connector, I tried to replace it entirely with dummy object and it still generates webroot

**Comment by DavertMik** [comment]
Yes, I didn't manage to mock it entirely so webroot is being created. 
Unfortunately I need to patch it in Codeception repo and only then this will be available here

**Comment by dmitry-kulikov** [comment]
Suggested an alternative https://github.com/Codeception/Codeception/pull/3381/files#r72553851, but don't know what is better.

**Comment by DavertMik** [comment]
Thanks, @dmitry-kulikov . This should be fixed with your proposal in latest Codeception (2.2.4, which is not released yet)
