### ISSUE TITLE
Running codeception from root with -c option, throws exception

### ISSUE THREAD

**Issue by Deele** [yiisoft/yii2-app-basic#8]
By following currently the only [guide for codeception in yii2](https://github.com/yiisoft/yii2-app-basic/blob/master/tests/README.md) I successfully ran the tests with command `c:\my\project\location\tests>codecept run` without errors.

But then, I was looking forward to creating a command in IDE I'm using (PhpStorm 8) to run those tests with shortcut and get an output within IDE.

As IDE rans commands relative to application root, I tried to test it from cmd.exe. I ran command similar to this: `c:\my\project\location>codecept -c c:\my\project\location\tests` (-c option to command codeception to use codeception.yml that resides in \tests dir) and got an error:

```
  [InvalidArgumentException]
  There are no commands defined in the "M" namespace.
```

Should I run a codecept command from application root in a different way?

I'm running yii2 app on Win7 station through wamp25 package that has php v5.5.x.

**Comment by samdark** [comment]
It should be run from app root.

**Comment by Deele** [comment]
My app root is `c:\my\project\location`. Running codecept from there, I get error:

```
c:\my\project\location>codecept run



  [Codeception\Exception\Configuration]
  Configuration file could not be found.
  Run `bootstrap` to initialize Codeception.
```

Command "codecept" is equal to `C:\Users\Deele\AppData\Roaming\Composer\vendor\bin\codecept.bat`.

@samdark Please, explain what should be run from where exactly.

**Comment by samdark** [comment]
`C:\Users\Deele\AppData\Roaming\Composer\vendor\bin\codecept.bat c:\my\project\location\tests`.

**Comment by samdark** [comment]
i.e. Codeception should be run from where your `codeception.yml` is.

**Comment by Deele** [comment]
That means, when using codeception with yii, it is not possible to load `codeception.yml` file from remote location, to run the tests.

Please, include similar comment into [readme](https://github.com/yiisoft/yii2-app-basic/blob/master/tests/README.md), because it is unusual behavior, as codeception is designed that one can use `-c [path to codeception.yml]` option to run `codecept` from anywhere. In addition, if that what I said is correct, that feature should be implemented. If it is not, consider this issue as closed.

**Comment by samdark** [comment]
I'll try running it with `-c` switch.

**Comment by samdark** [comment]
Unable to reproduce using current master code.

**Comment by k1cker** [comment]
try by this scenario
https://stackoverflow.com/questions/37568503/how-to-run-unit-tests-codeception-in-yii2-framework/37574099

**Comment by mycarrysun** [comment]
Adding the `-c` flag for the path of my `codeception.yml` file fixed my issue!
