### ISSUE TITLE
The Damn fxp/composer-asset-plugin weird problem is back!

### ISSUE THREAD

**Issue by pareekbhagu** [yiisoft/yii2-app-basic#83]
### What steps will reproduce the problem?
1. I cloned a forked version of official yii2-app-basic in my local machine.
2. update composer asset plugin to 1.1.3
3. git push origin master.
4. my app is connected to heroku through github ( automatically deployed when i push to github).

### What's expected?
While it should work as it works locally,
### What do you get instead?
I get '/app/vendor/bower/jquery/dist' can't publish to the directory error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |
| PHP version      |
| Operating system |

**Comment by samdark** [comment]
Do you have fxp installed globally prior to running install/update? If not, delete vendor directory then install fpx globally.

**Comment by pareekbhagu** [comment]
For the time being I adopted an ugly solution to make it work. But shall reinstall it according to the steps you mentioned and then respond.
