### ISSUE TITLE
Unit test parent class (dev)

### ISSUE THREAD

**Issue by KorDum** [yiisoft/yii2-app-basic#84]
### What steps will reproduce the problem?

Create class `TestCase extends yii\codeception\DbTestCase` in `./tests/unit` with namespace `tests\unit`

Extend any test class from `./tests/unit/models`

```
namespace tests\models;
import tests\unit\TestCase;
class LoginFormTest extends TestCase
```

Add (or not) in ./tests/_bootstrap.php

```
Yii::setAlias('@tests', dirname(__DIR__));
```

Run unit tests
### What's expected?

PHP Fatal error:  Class 'tests\unit\TestCase' not found in [TestClass.php] on line ...
I tryed namespase `app\tests\unit` instead `tests\unit` also.
### What do you get instead?

Runned tests.
### Additional info

| Q | A |
| --- | --- |
| Yii vesion | 2.0.9 |
| PHP version | 5.6.23 |
| Operating system | Windows 10 x64 |

**Comment by SilverFire** [comment]
> import tests\unit\TestCase;

What it `import`?

**Comment by KorDum** [comment]
Sorry, it's a typo, in my text there only.
`use` instead of carse.

**Comment by KorDum** [comment]
This issue works fine if in ```./tests/unit/_bootstrap.php``` add new line:
```require_once __DIR__ . '/TestCase.php';```

**Comment by SilverFire** [comment]
See [Codeception autoloading](http://codeception.com/docs/reference/Autoload) guide page.

Add `\Codeception\Util\Autoload::addNamespace('tests', __DIR__);` to `bootstrap.php` to make it work.

@DavertMik do you think we should add it by default?
