### ISSUE TITLE
the fxp/composer-asset-plugin keeps haunting ... 

### ISSUE THREAD

**Issue by pareekbhagu** [yiisoft/yii2-app-basic#85]
@samdark ### What steps will reproduce the problem?
trying to push to heroku master.. 
tried everything like 
`php composer.phar global update fxp/composer-asset-plugin --no-plugins`

tried changing the require section of composer.json..  
heroku rejects the push due to fxp/composer-asset-plugin......
kindly help.

**Comment by cebe** [comment]
you need `global require`, not `global update`
