### ISSUE TITLE
Add composer.lock to .gitignore

### ISSUE THREAD

**Issue by sasha-ch** [yiisoft/yii2-app-basic#88]
I see some difference between 
https://github.com/yiisoft/yii2/blob/master/.gitignore
https://github.com/yiisoft/yii2-app-basic/blob/master/.gitignore
https://github.com/yiisoft/yii2-app-advanced/blob/master/.gitignore
Is it reasonable? Or may we add `composer.lock` to `.gitignore`?

**Comment by samdark** [comment]
It's OK. It should not be gitignored.
